import { resolveMohaveParcel } from "../../../lib/parcel-resolver";
const QUERY="https://mcgis.mohave.gov/arcgis/rest/services/PARCELS/MapServer/14/query";
const clean=(value:string)=>value.replaceAll("'","''").trim().slice(0,160);
const summary=(feature:any)=>{const a=feature.attributes||{};return {apn:String(a.PARCEL||a.TAXPIN||""),address:String(a.SITE_ADDRESS||""),owner:String(a.OWNER||""),acres:Number(a.PARCEL_SIZE)||null,unit:String(a.UNIT_TYPE||"ACRES"),useCode:String(a.USE_CODE||a.PROPUSE||""),propertyCode:String(a.PROPCODE||""),fullCashValue:Number(a.FULL_CASH_VALUE||a.ASSESSED_FULL_CASH_VALUE)||null,latitude:Number(a.LATITUDE)||null,longitude:Number(a.LONGITUDE)||null}};
async function query(params:URLSearchParams){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),20000);try{const response=await fetch(QUERY,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded",Accept:"application/json"},body:params.toString(),signal:controller.signal,cache:"no-store"});if(!response.ok)throw new Error("HTTP "+response.status);const data=await response.json();if(data.error)throw new Error(data.error.message||"County query failed");return data.features||[]}finally{clearTimeout(timer)}}
export async function GET(request:Request){
  try{const url=new URL(request.url),type=url.searchParams.get("type")||"apn",value=String(url.searchParams.get("value")||"").trim();
    if(type==="apn"){const parcel:any=await resolveMohaveParcel(value);if(parcel.status!=="resolved")return Response.json({ok:false,error:"No exact Mohave County APN match was returned."},{status:404});return Response.json({ok:true,matchQuality:"exact",candidates:[summary({attributes:parcel.attributes})]})}
    let params:URLSearchParams;
    if(type==="address"){if(value.length<4)return Response.json({ok:false,error:"Enter enough of the street address to identify the property."},{status:400});params=new URLSearchParams({where:"SITE_ADDRESS LIKE '%"+clean(value).toUpperCase()+"%'",outFields:"PARCEL,TAXPIN,SITE_ADDRESS,OWNER,PARCEL_SIZE,UNIT_TYPE,USE_CODE,PROPUSE,PROPCODE,FULL_CASH_VALUE,ASSESSED_FULL_CASH_VALUE,LATITUDE,LONGITUDE",returnGeometry:"false",resultRecordCount:"10",f:"json"})}
    else if(type==="coordinates"){const parts=value.split(",").map(Number);if(parts.length!==2||!parts.every(Number.isFinite))return Response.json({ok:false,error:"Enter coordinates as latitude, longitude."},{status:400});const [lat,lon]=parts;params=new URLSearchParams({geometry:JSON.stringify({x:lon,y:lat,spatialReference:{wkid:4326}}),geometryType:"esriGeometryPoint",inSR:"4326",spatialRel:"esriSpatialRelIntersects",outFields:"PARCEL,TAXPIN,SITE_ADDRESS,OWNER,PARCEL_SIZE,UNIT_TYPE,USE_CODE,PROPUSE,PROPCODE,FULL_CASH_VALUE,ASSESSED_FULL_CASH_VALUE,LATITUDE,LONGITUDE",returnGeometry:"false",resultRecordCount:"10",f:"json"})}
    else return Response.json({ok:false,error:"Unsupported property identifier."},{status:400});
    const candidates=(await query(params)).map(summary);return Response.json({ok:Boolean(candidates.length),matchQuality:candidates.length===1?"single_candidate":"candidate_list",candidates,error:candidates.length?undefined:"No matching Mohave County parcel was returned."},{status:candidates.length?200:404});
  }catch(error){return Response.json({ok:false,error:error instanceof Error?error.message:"Property lookup failed."},{status:500})}
}
