const SERVICE="https://services.arcgis.com/C34zQ7veRS0V1t04/ArcGIS/rest/services/Well_Registry_2024/FeatureServer/0/query";
const FIELDS="REGISTRY_ID,OWNER_NAME,WELLTYPE,WELL_TYPE_GROUP,DLIC_NUM,APPROVED,INSTALLED,WELL_DEPTH,WATER_LEVEL,CASING_DEPTH,CASING_DIAMETER,CASING_TYPE,PUMP_TYPE,PUMP_POWER,PUMPRATE,TESTEDRATE,DRAW_DOWN,COMPLETION_REPORT_STATUS,DRILL_LOG,WELL_CANCELLED,CADASTRAL,COUNTY,WATERSHED,BASIN_NAME,SUBBASIN_NAME,AMA,APPLICATION_DATE,WATER_USE,SITE_USE";

async function query(params:URLSearchParams){let last="Unknown ADWR service error";for(let attempt=1;attempt<=3;attempt++){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),25000);try{const response=await fetch(SERVICE,{method:"POST",signal:controller.signal,headers:{Accept:"application/json","Content-Type":"application/x-www-form-urlencoded"},body:params.toString(),cache:"no-store"});if(!response.ok)throw new Error(`HTTP ${response.status}`);const data=await response.json();if(data.error)throw new Error(data.error.message||"ADWR ArcGIS error");return data}catch(error){last=error instanceof Error?error.message:"Unknown error";if(attempt<3)await new Promise(resolve=>setTimeout(resolve,attempt*700))}finally{clearTimeout(timer)}}throw new Error(last)}
function haversineMiles(a:{latitude:number;longitude:number},b:{latitude:number;longitude:number}){const r=3958.7613;const rad=(x:number)=>x*Math.PI/180;const dLat=rad(b.latitude-a.latitude),dLon=rad(b.longitude-a.longitude);const h=Math.sin(dLat/2)**2+Math.cos(rad(a.latitude))*Math.cos(rad(b.latitude))*Math.sin(dLon/2)**2;return 2*r*Math.asin(Math.sqrt(h))}
function normalize(feature:any,centroid:any,match:"on_parcel"|"nearby"){const a=feature.attributes||{};const location={longitude:Number(feature.geometry?.x),latitude:Number(feature.geometry?.y)};const registry=String(a.REGISTRY_ID||"");return {...a,registrationNumber:registry?`55-${registry}`:null,match,distanceMiles:Number.isFinite(location.latitude)&&centroid?Number(haversineMiles(centroid,location).toFixed(3)):null,location,detailUrl:registry?`https://app.azwater.gov/WellRegistry/Detail.aspx?RegID=${registry}`:null,imagedRecordsUrl:"https://infoshare.azwater.gov/docushare/dsweb/HomePage"}}

export async function resolveAdwrWells(parcel:any,radiusMiles=2){
  if(!parcel?.geometry||!parcel?.centroid?.latitude||!parcel?.centroid?.longitude)return {status:"blocked",reason:"Validated parcel geometry and centroid are required.",source:SERVICE,onParcel:[],nearby:[]};
  try{
    const base={inSR:"4326",outFields:FIELDS,returnGeometry:"true",outSR:"4326",f:"json"};
    const exactParams=new URLSearchParams({...base,geometry:JSON.stringify(parcel.geometry),geometryType:"esriGeometryPolygon",spatialRel:"esriSpatialRelIntersects"});
    const nearbyParams=new URLSearchParams({...base,geometry:`${parcel.centroid.longitude},${parcel.centroid.latitude}`,geometryType:"esriGeometryPoint",distance:String(radiusMiles),units:"esriSRUnit_StatuteMile",spatialRel:"esriSpatialRelIntersects",resultRecordCount:"250"});
    const [exactData,nearbyData]=await Promise.all([query(exactParams),query(nearbyParams)]);const exactIds=new Set((exactData.features||[]).map((x:any)=>String(x.attributes?.REGISTRY_ID)));
    const onParcel=(exactData.features||[]).map((x:any)=>normalize(x,parcel.centroid,"on_parcel"));const nearby=(nearbyData.features||[]).filter((x:any)=>!exactIds.has(String(x.attributes?.REGISTRY_ID))).map((x:any)=>normalize(x,parcel.centroid,"nearby")).sort((a:any,b:any)=>(a.distanceMiles??999)-(b.distanceMiles??999)).slice(0,25);
    const usable=nearby.filter((x:any)=>Number(x.WELL_DEPTH)>0&&Number(x.WATER_LEVEL)>0);const depths=usable.map((x:any)=>Number(x.WELL_DEPTH));const levels=usable.map((x:any)=>Number(x.WATER_LEVEL));
    return {status:"queried",source:SERVICE,officialDisclaimer:"ADWR registry information is reported by well owners and drillers and is not independently verified by ADWR.",radiusMiles,onParcel,nearby,comparison:{usableNearbyWells:usable.length,depthRangeFeet:depths.length?[Math.min(...depths),Math.max(...depths)]:null,waterLevelRangeFeet:levels.length?[Math.min(...levels),Math.max(...levels)]:null,note:"Nearby wells provide local context, not a guarantee of water availability, depth, quality or yield on the subject parcel."}};
  }catch(error){return {status:"temporarily_unavailable",source:SERVICE,error:error instanceof Error?error.message:"ADWR query failed",onParcel:[],nearby:[]}}
}
