const SOURCE="https://mcgis.mohave.gov/arcgis/rest/services/PARCELS/MapServer/17/query";

async function queryOne(apn:string){
  const body=new URLSearchParams({where:`TAXPIN='${apn.replace(/'/g,"''")}'`,outFields:"TAXPIN,BLTASDESCRIPTION,CLASSDESCRIPTION,BLTASYEARBUILT,BLTASSTORIES,SF,PROPERTYTYPE,IMPNO",returnGeometry:"false",resultRecordCount:"2000",f:"json"});let lastError="Improvement query failed";
  for(let attempt=1;attempt<=2;attempt++){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),20000);try{const response=await fetch(SOURCE,{method:"POST",signal:controller.signal,headers:{Accept:"application/json","Content-Type":"application/x-www-form-urlencoded"},body:body.toString(),cache:"no-store"});if(!response.ok)throw new Error(`HTTP ${response.status}`);const text=await response.text();if(!text.trim().startsWith("{"))throw new Error("County improvement service returned a non-JSON response");const data=JSON.parse(text);if(data.error)throw new Error(data.error.message||"ArcGIS error");return {apn,features:data.features||[],error:null}}catch(error){lastError=error instanceof Error?error.message:"Improvement query failed";if(attempt<2)await new Promise(resolve=>setTimeout(resolve,400))}finally{clearTimeout(timer)}}return {apn,features:[],error:lastError};
}

export async function resolveBuildingDetails(apns:string[]){
  const unique=[...new Set(apns.filter(Boolean))].slice(0,60),parcels:Record<string,any>={},diagnostics:any[]=[];
  for(let offset=0;offset<unique.length;offset+=5){const results=await Promise.all(unique.slice(offset,offset+5).map(queryOne));for(const result of results){diagnostics.push({apn:result.apn,status:result.error?"unavailable":result.features.length?"matched":"no_records",featureCount:result.features.length,error:result.error});for(const feature of result.features){const x=feature.attributes||{},apn=String(x.TAXPIN||result.apn);parcels[apn]||={apn,improvementMap:new Map<string,any>()};const key=[x.IMPNO,x.BLTASDESCRIPTION,x.BLTASYEARBUILT,x.SF].join("|");const existing=parcels[apn].improvementMap.get(key);if(existing){existing.sourcePropertyTypes=[...new Set([...existing.sourcePropertyTypes,x.PROPERTYTYPE].filter(Boolean))];existing.sourceStoryValues=[...new Set([...existing.sourceStoryValues,x.BLTASSTORIES].filter((v:any)=>v!==null))];if(!existing.constructionClass&&x.CLASSDESCRIPTION)existing.constructionClass=x.CLASSDESCRIPTION;if(Number(x.BLTASSTORIES)>Number(existing.stories||0))existing.stories=x.BLTASSTORIES;if(String(x.PROPERTYTYPE||"").toLowerCase()==="residential")existing.propertyType="Residential"}else parcels[apn].improvementMap.set(key,{improvementNumber:x.IMPNO,description:x.BLTASDESCRIPTION,constructionClass:x.CLASSDESCRIPTION,yearBuilt:x.BLTASYEARBUILT,stories:x.BLTASSTORIES,squareFeet:x.SF,propertyType:x.PROPERTYTYPE,sourcePropertyTypes:[x.PROPERTYTYPE].filter(Boolean),sourceStoryValues:[x.BLTASSTORIES].filter((v:any)=>v!==null)})}}}
  for(const parcel of Object.values(parcels) as any[]){parcel.improvements=[...parcel.improvementMap.values()];delete parcel.improvementMap;const residences=parcel.improvements.filter((x:any)=>String(x.propertyType||"").toLowerCase()==="residential"||/house|residence|ranch|dwelling/i.test(String(x.description||""))).sort((a:any,b:any)=>Number(b.squareFeet||0)-Number(a.squareFeet||0));parcel.primaryResidence=residences[0]||null;parcel.accessoryImprovements=parcel.improvements.filter((x:any)=>!residences.includes(x));parcel.totalUniqueImprovementArea=parcel.improvements.reduce((sum:number,x:any)=>sum+Number(x.squareFeet||0),0)}
  return {status:diagnostics.some(x=>x.status==="unavailable")?"partial":"queried",source:SOURCE,sourceName:"Mohave County Assessor improvement characteristics",parcels,diagnostics};
}
