export type EvidenceAsset={id:string;category:string;title:string;status:"Verified match"|"Geographic intersection"|"Supporting record"|"Human retrieval required";summary:string;sourceUrl:string;documentUrl?:string;imageUrl?:string;identifiers?:string[]};
export type EvidencePackage={generatedAt:string;parcelMapUrl?:string;zoningMapUrl?:string;floodMapUrl?:string;assets:EvidenceAsset[];disclaimer:string};

function investigation(items:any[],kind:string){return items.find(x=>x.kind===kind)?.directEvidence||{}}
function bbox(parcel:any){const points=(parcel?.geometry?.rings||[]).flat();if(!points.length)return null;const xs=points.map((p:any)=>Number(p[0])),ys=points.map((p:any)=>Number(p[1]));const pad=.002;return `${Math.min(...xs)-pad},${Math.min(...ys)-pad},${Math.max(...xs)+pad},${Math.max(...ys)+pad}`}
function mapUrl(service:string,box:string,layers:string){const p=new URLSearchParams({bbox:box,bboxSR:"4326",imageSR:"4326",size:"1200,800",format:"png32",transparent:"false",f:"image",layers:`show:${layers}`});return `${service}/export?${p}`}

export function buildEvidencePackage(investigations:any[]):EvidencePackage{
  const parcelEvidence=investigation(investigations,"parcel"),recorderEvidence=investigation(investigations,"recorder"),waterEvidence=investigation(investigations,"water"),zoningEvidence=investigation(investigations,"zoning");
  const parcel=parcelEvidence.county||zoningEvidence.county||waterEvidence.county||recorderEvidence.county,overlays=parcelEvidence.spatial||zoningEvidence.spatial||recorderEvidence.spatial,zoning=parcelEvidence.zoningRules||zoningEvidence.zoningRules,wells=parcelEvidence.wells||waterEvidence.wells,soils=parcelEvidence.soils||waterEvidence.soils,recorder=recorderEvidence.recorder,market=parcelEvidence.market,box=bbox(parcel);const assets:EvidenceAsset[]=[];
  if(parcel?.status==="resolved")assets.push({id:"parcel",category:"Parcel",title:`Mohave County parcel ${parcel.attributes?.PARCEL||parcel.attributes?.TAXPIN}`,status:"Verified match",summary:`Exact APN match; ${parcel.attributes?.PARCEL_SIZE} ${parcel.attributes?.UNIT_TYPE||"acres"}; ${parcel.attributes?.LEGAL_DESCRIPTION||"legal description returned"}.`,sourceUrl:`${parcel.service}/${parcel.layer}`,identifiers:[parcel.attributes?.ACCOUNTNO,parcel.attributes?.RECPTNO].filter(Boolean)});
  for(const item of overlays?.conclusions||[])assets.push({id:`overlay-${item.topic}`,category:item.topic.replaceAll("_"," "),title:item.statement,status:item.status==="parcel_matched"?"Verified match":"Geographic intersection",summary:item.topic==="right_of_way_abandonment"?"Mapped intersection requires instrument-level interpretation; it is not treated as a title conclusion.":item.statement,sourceUrl:(overlays.results||[]).find((x:any)=>x.id===item.topic||item.topic.startsWith(x.id))?.source||"https://mcgis.mohave.gov/"});
  if(zoning?.status==="parcel_matched")assets.push({id:"zoning-rules",category:"Zoning",title:`${zoning.combiningZone||zoning.zone} development-rule screen`,status:"Verified match",summary:zoning.conclusion,sourceUrl:zoning.sources?.ar||"https://www.mohave.gov/departments/development-services/planning-zoning-division/",identifiers:[zoning.combiningZone].filter(Boolean)});
  for(const well of wells?.onParcel||[])assets.push({id:`well-${well.REGISTRY_ID}`,category:"Water",title:`ADWR Well Registry ${well.registrationNumber}`,status:"Verified match",summary:`On-parcel registry point; reported depth ${well.WELL_DEPTH??"unknown"} ft, water level ${well.WATER_LEVEL??"unknown"} ft, casing ${well.CASING_DEPTH??"unknown"} ft. Registry data is owner/driller reported.`,sourceUrl:wells.source,documentUrl:well.detailUrl,identifiers:[well.registrationNumber,well.CADASTRAL].filter(Boolean)});
  for(const unit of soils?.mapUnits||[])assets.push({id:`soil-${unit.mukey}`,category:"Soils / septic",title:`SSURGO ${unit.musym}: ${unit.muname}`,status:"Geographic intersection",summary:`Dominant components: ${(unit.dominantComponents||[]).map((x:any)=>`${x.name} ${x.percent}%${x.hydrologicGroup?`, HSG ${x.hydrologicGroup}`:""}${x.restrictionDepthInches?`, restriction ${x.restrictionDepthInches} in`:""}`).join("; ")}.`,sourceUrl:soils.source,identifiers:[unit.mukey,unit.musym].filter(Boolean)});
  for(const survey of recorder?.surveys||[])for(const doc of survey.documents||[])assets.push({id:`survey-${survey.bookPage}-${doc.description}`,category:"Survey / access",title:`Record of Survey ${survey.bookPage} — ${doc.description}`,status:"Supporting record",summary:"County-hosted survey image retrieved automatically; review geometry, dedications and notes before relying on access conclusions.",sourceUrl:doc.pdfUrl,documentUrl:doc.pdfUrl,identifiers:[survey.bookPage,doc.description]});
  for(const lead of recorder?.leads||[])if(lead.retrieval==="recorder_checkpoint")assets.push({id:lead.id,category:"Recorder / title",title:`${lead.reference}: ${lead.role}`,status:"Human retrieval required",summary:"Exact fee-number search prepared. Recorder terms acceptance and CAPTCHA must be completed by a human; upload the matching image for preservation and analysis.",sourceUrl:lead.sourceUrl,identifiers:[lead.reference]});
  if(market?.derived)assets.push({id:"market",category:"Market",title:"Assessor-recorded comparable-sale screen",status:"Supporting record",summary:market.derived.conclusion,sourceUrl:market.source,identifiers:[`${market.derived.primaryComparableCount} primary`,`${market.derived.secondaryComparableCount} secondary`]});
  return {generatedAt:new Date().toISOString(),parcelMapUrl:box?mapUrl("https://mcgis.mohave.gov/arcgis/rest/services/PARCELS/MapServer",box,"14"):undefined,zoningMapUrl:box?mapUrl("https://mcgis.mohave.gov/arcgis/rest/services/PZ_GeneralPlanNewStyle/MapServer",box,"19,2"):undefined,floodMapUrl:box?mapUrl("https://hazards.fema.gov/arcgis/rest/services/public/NFHL/MapServer",box,"28"):undefined,assets,disclaimer:"This appendix preserves automated source matches and retrieval links. Map intersections are screening evidence, not surveys, title opinions, permits, engineering conclusions or guarantees of source accuracy."};
}
