function conclusion(overlays:any,topic:string){return overlays?.conclusions?.find((x:any)=>x.topic===topic)}
function firstParcelBuilding(buildings:any){return Object.values(buildings?.parcels||{})[0] as any}

export function resolveHighestBestUse(parcel:any,buildings:any,overlays:any,zoning:any,landDivision:any,wells:any,soils:any,market:any){
  const flood=conclusion(overlays,"flood"),row=conclusion(overlays,"right_of_way"),abandonment=conclusion(overlays,"right_of_way_abandonment"),roads=conclusion(overlays,"road_adjacency"),improvements=firstParcelBuilding(buildings),onParcelWells=wells?.onParcel||[],mapUnits=soils?.mapUnits||[];
  const restrictiveSoils=mapUnits.some((u:any)=>(u.dominantComponents||[]).some((c:any)=>c.hydrologicGroup==="D"||Number(c.restrictionDepthInches)>0));
  const evidence={
    zoning:`${zoning?.combiningZone||zoning?.zone||"Unresolved zoning"}; ${zoning?.parcelAcres||parcel?.attributes?.PARCEL_SIZE||"unknown"} acres`,
    existingImprovements:(improvements?.improvements||[]).map((x:any)=>`${x.description}${x.squareFeet?` ${x.squareFeet} SF`:""}${x.yearBuilt?`, built ${x.yearBuilt}`:""}`),
    flood:flood?.statement||"FEMA intersection unresolved",access:row?.statement||roads?.statement||"Access mapping unresolved",accessConflict:abandonment?.statement||null,
    water:onParcelWells.length?`ADWR registry returns ${onParcelWells.map((x:any)=>x.registrationNumber).join(", ")} on the parcel; registry depth ${onParcelWells[0]?.WELL_DEPTH??"unknown"} feet and reported water level ${onParcelWells[0]?.WATER_LEVEL??"unknown"} feet.`:"No on-parcel ADWR registry point returned.",
    soils:mapUnits.map((x:any)=>x.muname),market:market?.derived?.conclusion||"Market valuation evidence not available"
  };
  const options=[
    {use:"Existing rural estate / primary residence",score:92,classification:"highest_supported_use",legalPath:"As-of-right residential continuation under A-R/36A",supports:["Existing assessor-identified primary residence and equipment building","A-R permits a principal single-family residence","FEMA Zone X minimal-hazard intersection","On-parcel domestic well registry match"],constraints:["Confirm zoning cadastral conflict in writing","Resolve the mapped Panther Pass abandonment against active access instruments","Verify well performance, potable quality and septic permit/capacity"],economicStatus:"Market-supported concept; exact value withheld pending a third primary comparable and property-condition inputs"},
    {use:"One-parcel cottage / accessory-residence compound",score:74,classification:"promising_expansion_path",legalPath:"Keep one legal parcel and use current accessory-residence allowances",supports:[`County rule screen indicates up to ${zoning?.accessoryResidences?.totalPotentialAccessoryResidences??"multiple"} accessory residences for this acreage`,"No land split or ADRE subdivision filing solely from retaining one fee parcel","Existing residence, equipment building, road adjacency and well provide a development base"],constraints:["Planning confirmation of unit count, building type and site plan","Engineered wastewater feasibility; SSURGO indicates rock, slopes and hydrologic C/D soils","Fire apparatus access and stored-water review","Well yield and legal service arrangement for added demand","No separate lot or fractional-interest marketing"],economicStatus:"Potentially marketable affordable-housing/rental product; demand, rents, construction budget and operating model still require testing"},
    {use:"Two-to-five-lot land division",score:28,classification:"blocked_by_current_zoning",legalPath:"Density-increasing rezone followed by Mohave parcel-plat review",supports:["State/county minor-land-division process exists","Mapped roadway/easement evidence provides a starting access record"],constraints:[landDivision?.subjectConclusion||"Current zoning yield unresolved","Rezone is discretionary","Surveyed net acreage, access, utility easements, water and sewage methods required","Serial splitting cannot be used to evade subdivision rules"],economicStatus:"Do not underwrite until Planning gives a plausible zoning path and a surveyor produces net yield"},
    {use:"Six-or-more-lot residential subdivision",score:18,classification:"major_entitlement_path",legalPath:"Rezone, subdivision plat, ADRE Public Report and ADWR water-supply process",supports:["Arizona law supplies a defined subdivision pathway"],constraints:["Current 36-acre minimum produces only one whole zoning-sized lot","Public Report required before advertising/offers unless exempt","Water adequacy, engineered roads/drainage, wastewater and assurances","Rocky/sloping soils can materially increase infrastructure cost"],economicStatus:"Not a credible present HBU for this 38.21-acre parcel without a major entitlement and infrastructure program"},
    {use:"RV park",score:24,classification:"special_use_high_infrastructure",legalPath:"Special Use Permit under A-R plus park, wastewater, access and fire approvals",supports:["A-R provides an SUP pathway","Parcel exceeds the stated minimum park acreage"],constraints:["Discretionary SUP","Central or otherwise approved wastewater solution","Internal roads/turnarounds, utilities and fire protection","Terrain/rock and water capacity","No parcel-specific RV demand or revenue study"],economicStatus:"Possible use, but presently weaker than residential/compound use and not financially demonstrated"},
    {use:"Manufactured-home park",score:21,classification:"special_use_high_infrastructure",legalPath:"Special Use Permit plus manufactured-home-park standards",supports:["A-R provides an SUP pathway","Parcel exceeds the stated minimum park acreage"],constraints:["Discretionary SUP","Approved wastewater system and internal streets","Water, fire, installation and space standards","No parcel-specific absorption or operating analysis"],economicStatus:"Legally investigable, but presently speculative and infrastructure-heavy"},
    {use:"General commercial development",score:10,classification:"not_supported_by_current_evidence",legalPath:"General Plan/zoning change and project-specific entitlements",supports:[],constraints:["A-R/Rural Development Area evidence does not establish commercial zoning","Remote rural access and infrastructure","Commercial comparable set is not physically or locationally comparable and must not drive subject value"],economicStatus:"Reject as present HBU unless a specific commercial demand generator and entitlement path are supplied"}
  ];
  if(restrictiveSoils)for(const option of options)if(option.use.includes("subdivision")||option.use.includes("park")||option.use.includes("compound"))option.score=Math.max(0,option.score-4);
  options.sort((a,b)=>b.score-a.score);
  return {status:"ranked_evidence_screen",scoreMeaning:"0–100 relative legal/physical feasibility score for prioritizing investigation; it is not an appraisal, profit forecast or approval probability.",ranking:options.map((x,i)=>({rank:i+1,...x})),recommendedStrategy:{primary:options[0].use,expansion:options.find(x=>x.use.includes("cottage"))?.use,hold:"Do not pursue separate-lot marketing under current A-R/36A zoning.",reason:"Existing rural-residential improvements, permitted-use alignment, FEMA Zone X and an on-parcel well registry match support the estate use. A one-parcel accessory-residence strategy adds attainable-housing potential without pretending the parcel can presently support a conforming split."},evidence,criticalDecisionInputs:["Written Planning confirmation of A-R/36A and the conflicting township/range/section attributes","Septic permit and capacity plus site-specific soils/percolation or engineered wastewater feasibility","Well 55-230892 drill log, pump/yield test and water-quality results","Survey/title interpretation of Boulder Pass, Panther Pass and BOS Resolution 2022-203","Fire-service access and stored-water requirements","Property condition/amenities and at least one additional verified primary comparable"],sources:[...Object.values(zoning?.sources||{}),...Object.values(landDivision?.sources||{}),wells?.source,soils?.source].filter(Boolean)};
}
