const PARCEL_QUERY="https://mcgis.mohave.gov/arcgis/rest/services/PARCELS/MapServer/14/query";
const MILES_TO_METERS=1609.344;

function number(value:unknown){const n=Number(value);return Number.isFinite(n)?n:null}
function haversineMiles(aLat:number,aLon:number,bLat:number,bLon:number){const r=3958.7613;const rad=Math.PI/180;const dLat=(bLat-aLat)*rad,dLon=(bLon-aLon)*rad;const h=Math.sin(dLat/2)**2+Math.cos(aLat*rad)*Math.cos(bLat*rad)*Math.sin(dLon/2)**2;return 2*r*Math.asin(Math.sqrt(h))}
function classification(x:any){const improvement=number(x.IMPVALUE)||0;const code=String(x.PROPCODE||"").toLowerCase();if(code.includes("commercial"))return "commercial";if(improvement>1000||code.includes("residential"))return "improved_residential";return "vacant_land"}
function median(values:number[]){if(!values.length)return null;const sorted=[...values].sort((a,b)=>a-b);const middle=Math.floor(sorted.length/2);return sorted.length%2?sorted[middle]:(sorted[middle-1]+sorted[middle])/2}
function percentile(values:number[],p:number){if(!values.length)return null;const sorted=[...values].sort((a,b)=>a-b);const index=(sorted.length-1)*p;const lower=Math.floor(index),upper=Math.ceil(index);return lower===upper?sorted[lower]:sorted[lower]+(sorted[upper]-sorted[lower])*(index-lower)}

export async function resolveMarketComps(parcel:any,radiusMiles=15){
  const lat=number(parcel?.centroid?.latitude),lon=number(parcel?.centroid?.longitude);const subjectAcreage=number(parcel?.attributes?.PARCEL_SIZE);if(lat===null||lon===null)return {status:"blocked",reason:"Validated parcel centroid is required."};
  const params=new URLSearchParams({geometry:JSON.stringify({x:lon,y:lat,spatialReference:{wkid:4326}}),geometryType:"esriGeometryPoint",inSR:"4326",distance:String(radiusMiles*MILES_TO_METERS),units:"esriSRUnit_Meter",spatialRel:"esriSpatialRelIntersects",where:"SALEP > 0",outFields:"PARCEL,SITE_ADDRESS,SALEP,SALEDT,DEEDTYPE,RECPTNO,PARCEL_SIZE,UNIT_TYPE,PROPCODE,PROPTYPE,ABSTDESCR,FULL_CASH_VALUE,LANDVALUE,IMPVALUE,LATITUDE,LONGITUDE,LEGAL_DESCRIPTION",returnGeometry:"false",resultRecordCount:"2000",orderByFields:"SALEDT DESC",f:"json"});
  const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),30000);
  try{
    const response=await fetch(PARCEL_QUERY,{method:"POST",signal:controller.signal,headers:{Accept:"application/json","Content-Type":"application/x-www-form-urlencoded"},body:params.toString(),cache:"no-store"});if(!response.ok)throw new Error(`HTTP ${response.status}`);const data=await response.json();if(data.error)throw new Error(data.error.message||"ArcGIS query failed");
    const subjectApn=String(parcel?.attributes?.PARCEL||parcel?.attributes?.TAXPIN||"");const cutoff=Date.now()-6*365.25*86400000;const candidates=(data.features||[]).map((f:any)=>f.attributes||{}).filter((x:any)=>x.PARCEL!==subjectApn&&number(x.SALEDT)!==null&&Number(x.SALEDT)>=cutoff&&number(x.SALEP)!==null&&Number(x.SALEP)>=5000&&number(x.PARCEL_SIZE)!==null&&Number(x.PARCEL_SIZE)>0).map((x:any)=>{const acres=Number(x.PARCEL_SIZE),salePrice=Number(x.SALEP),distance=haversineMiles(lat,lon,Number(x.LATITUDE),Number(x.LONGITUDE));const acreageRatio=subjectAcreage?Math.max(acres/subjectAcreage,subjectAcreage/acres):1;const deed=String(x.DEEDTYPE||"").toUpperCase();const flags=[deed&&!["WD","SWD","SD"].includes(deed)?`Review deed type ${deed}`:null,salePrice<10000?"Potential nominal/non-market consideration":null,acreageRatio>4?"Low acreage similarity":null].filter(Boolean);const score=Math.max(0,100-Math.min(distance,25)*2.2-Math.min(Math.abs(Math.log2(acreageRatio))*18,45)-(flags.length*8));return {...x,classification:classification(x),distanceMiles:Number(distance.toFixed(2)),salePricePerAcre:Number((salePrice/acres).toFixed(0)),similarityScore:Number(score.toFixed(1)),reviewFlags:flags}}).sort((a:any,b:any)=>b.similarityScore-a.similarityScore);
    const groups:any={vacant_land:[],improved_residential:[],commercial:[]};for(const item of candidates)if(groups[item.classification].length<15)groups[item.classification].push(item);
    const summarize=(items:any[])=>{const clean=items.filter(x=>!x.reviewFlags.some((flag:string)=>flag.includes("nominal")));const prices=clean.map(x=>Number(x.SALEP));const ppa=clean.map(x=>Number(x.salePricePerAcre));return {candidateCount:items.length,cleanCandidateCount:clean.length,medianSalePrice:median(prices),salePriceRange:prices.length?[Math.min(...prices),Math.max(...prices)]:null,medianPricePerAcre:median(ppa),pricePerAcreMiddleRange:ppa.length?[Math.round(percentile(ppa,.25)!),Math.round(percentile(ppa,.75)!)]:null,subjectIndicationFromMedianPpa:subjectAcreage&&ppa.length?Math.round(Number(subjectAcreage)*Number(median(ppa))):null}};
    const subjectClass=classification(parcel.attributes||{});return {status:"queried",source:PARCEL_QUERY,sourceName:"Mohave County Assessor parcel sale attributes",radiusMiles,lookbackYears:6,subject:{apn:subjectApn,classification:subjectClass,acreage:subjectAcreage,assessorSalePrice:number(parcel.attributes?.SALEP),assessorSaleDate:number(parcel.attributes?.SALEDT),fullCashValue:number(parcel.attributes?.FULL_CASH_VALUE),landValue:number(parcel.attributes?.LANDVALUE),improvementValue:number(parcel.attributes?.IMPVALUE)},groups:{vacantLand:{summary:summarize(groups.vacant_land),candidates:groups.vacant_land},improvedResidential:{summary:summarize(groups.improved_residential),candidates:groups.improved_residential},commercial:{summary:summarize(groups.commercial),candidates:groups.commercial}},derived:{primaryComparison:subjectClass==="vacant_land"?"vacantLand":subjectClass==="commercial"?"commercial":"improvedResidential",conclusion:"Assessor-recorded sale candidates are separated by property class and ranked by distance, acreage similarity, deed type and recency. They are screening evidence—not an appraisal or MLS-grade comparable-sales analysis.",nextVerification:"Verify top candidates against deed images, MLS/market status, improvements, condition, utilities, access and whether consideration was arm’s length before relying on a value range."}};
  }catch(error){return {status:"temporarily_unavailable",source:PARCEL_QUERY,error:error instanceof Error?error.message:"Comparable-sale query failed"}}finally{clearTimeout(timer)}
}
