const SERVICE="https://sdmdataaccess.sc.egov.usda.gov/Tabular/post.rest";
async function query(sql:string){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),45000);try{const response=await fetch(SERVICE,{method:"POST",signal:controller.signal,headers:{Accept:"application/json","Content-Type":"application/json"},body:JSON.stringify({format:"JSON+COLUMNNAME",query:sql}),cache:"no-store"});if(!response.ok)throw new Error(`HTTP ${response.status}`);const data=await response.json();if(!data.Table?.length)return [];const [headers,...rows]=data.Table;return rows.map((row:any[])=>Object.fromEntries(headers.map((h:string,i:number)=>[h,row[i]])))}finally{clearTimeout(timer)}}
function wkt(parcel:any){const ring=parcel?.geometry?.rings?.[0];if(!Array.isArray(ring)||ring.length<4)return null;const points=[...ring];if(points[0][0]!==points.at(-1)?.[0]||points[0][1]!==points.at(-1)?.[1])points.push(points[0]);return `POLYGON((${points.map((p:any)=>`${Number(p[0])} ${Number(p[1])}`).join(",")}))`}
function safeSql(value:string){return value.replaceAll("'","''")}

export async function resolveUsdaSoils(parcel:any){
  const polygon=wkt(parcel);if(!polygon)return {status:"blocked",reason:"A valid parcel polygon is required.",source:SERVICE,mapUnits:[],components:[],septicInterpretations:[]};
  try{
    const keys=await query(`SELECT * FROM SDA_Get_Mukey_from_intersection_with_WktWgs84('${safeSql(polygon)}')`);const mukeys=[...new Set<string>(keys.map((x:any)=>String(x.mukey)).filter((x:string)=>/^\d+$/.test(x)))];if(!mukeys.length)return {status:"queried",source:SERVICE,mapUnits:[],components:[],septicInterpretations:[],conclusion:"No SSURGO map unit was returned for the parcel polygon."};
    const list=mukeys.map(x=>`'${x}'`).join(",");
    const components=await query(`SELECT mu.mukey,mu.musym,mu.muname,c.cokey,c.compname,c.comppct_r,c.slope_r,c.hydgrp,c.drainagecl,c.taxorder,c.taxsubgrp,r.reskind,r.resdept_r FROM mapunit mu LEFT JOIN component c ON c.mukey=mu.mukey LEFT JOIN corestrictions r ON r.cokey=c.cokey WHERE mu.mukey IN (${list}) ORDER BY mu.mukey,c.comppct_r DESC`);
    const septic=await query(`SELECT c.mukey,c.compname,c.comppct_r,i.interphrc,i.interphr FROM cointerp i INNER JOIN component c ON c.cokey=i.cokey WHERE c.mukey IN (${list}) AND i.mrulename='ENG - Septic Tank Absorption Fields' ORDER BY c.mukey,c.comppct_r DESC`);
    const mapUnits=mukeys.map(key=>{const rows=components.filter((x:any)=>x.mukey===key);return {mukey:key,musym:rows[0]?.musym,muname:rows[0]?.muname,dominantComponents:rows.filter((x:any)=>Number(x.comppct_r)>=15).map((x:any)=>({name:x.compname,percent:Number(x.comppct_r),slopePercent:x.slope_r===null?null:Number(x.slope_r),hydrologicGroup:x.hydgrp,drainage:x.drainagecl,restriction:x.reskind,restrictionDepthInches:x.resdept_r===null?null:Number(x.resdept_r)}))}});
    const limitations=[...new Set(septic.map((x:any)=>x.interphrc).filter((x:any)=>x&&x!=="Not rated"&&!String(x).startsWith("Not rated;")))];const ratings=[...new Set(septic.map((x:any)=>x.interphrc).filter((x:any)=>x==="Very limited"||x==="Somewhat limited"||x==="Not limited"))];
    return {status:"queried",source:SERVICE,sourceName:"USDA NRCS Soil Data Access / SSURGO",mapUnits,components,septicInterpretations:septic,derived:{ratings,limitations,conclusion:ratings.includes("Very limited")?`SSURGO rates one or more dominant soil components as very limited for septic absorption fields. Principal mapped limitations: ${limitations.join(", ")}. A parcel-specific site investigation and percolation/design review remain necessary.`:"No dominant very-limited septic rating was returned; site investigation remains necessary."},disclaimer:"SSURGO is planning-level soil survey information and does not replace an onsite soil, percolation, engineering or permitting determination."};
  }catch(error){return {status:"temporarily_unavailable",source:SERVICE,error:error instanceof Error?error.message:"USDA soil query failed",mapUnits:[],components:[],septicInterpretations:[]}}
}
