function median(values:number[]){const a=[...values].filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return null;const m=Math.floor(a.length/2);return a.length%2?a[m]:Math.round((a[m-1]+a[m])/2)}
function money(value:number|null){return value===null?null:new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(value)}

export function resolveValuationNegotiation(parcel:any,market:any,highestBestUse:any,inputText=""){
  const subject=market?.subject||{},improved=market?.groups?.improvedResidential||{},primary=improved?.candidates?.filter((x:any)=>x.comparableTier==="primary"&&x.valuationEligible)||[],secondary=improved?.candidates?.filter((x:any)=>x.comparableTier==="secondary"&&x.valuationEligible)||[],vacant=market?.groups?.vacantLand?.candidates?.filter((x:any)=>x.valuationEligible)||[];
  const subjectClass=subject.classification,chosen=subjectClass==="vacant_land"?vacant:primary,prices=chosen.map((x:any)=>Number(x.SALEP)).filter((x:number)=>x>0),benchmark=median(prices),sufficient=chosen.length>=3;
  const assessorFcv=Number(parcel?.attributes?.FULL_CASH_VALUE||0),askingMatch=inputText.match(/asking\s*price[^\d]{0,20}\$?([\d,]+)/i),askingPrice=askingMatch?Number(askingMatch[1].replaceAll(",","")):null;
  const comparableTable=[...primary,...secondary].slice(0,8).map((x:any)=>({apn:x.PARCEL,address:x.SITE_ADDRESS||"No situs address returned",salePrice:x.SALEP,saleDate:x.SALEDT,distanceMiles:x.distanceMiles,acres:x.PARCEL_SIZE,residenceSquareFeet:x.buildingDetails?.primaryResidence?.squareFeet||x.buildingDetails?.totalUniqueImprovementArea||null,tier:x.comparableTier,pricePerResidenceSquareFoot:x.salePricePerResidenceSqFt,flags:x.reviewFlags||[]}));
  const leverage=[
    {topic:"Comparable support",strength:primary.length>=3?"moderate":"strong",finding:`Only ${primary.length} primary and ${secondary.length} secondary assessor-sale candidates presently qualify.`,negotiationUse:primary.length>=3?"Use the verified range as a pricing anchor, then adjust only for documented differences.":"Resist an unsupported premium and require MLS/deed verification or an appraisal before accepting a firm value conclusion."},
    {topic:"Access/title uncertainty",strength:"strong",finding:"Active Boulder Pass/Panther Pass right-of-way evidence overlaps a mapped Panther Pass abandonment.",negotiationUse:"Make title/access approval a contingency; seek a price concession, cure, or termination right if the controlling instruments reduce access."},
    {topic:"Zoning record conflict",strength:"moderate",finding:"The exact-APN zoning feature supports A-R/36A but its cadastral attributes conflict with the parcel legal record.",negotiationUse:"Require written Planning confirmation before valuing accessory-residence or entitlement upside."},
    {topic:"Water",strength:"moderate",finding:"ADWR registry evidence identifies an on-parcel well, but registry location and construction data do not prove present yield, potability or legal service capacity.",negotiationUse:"Condition value attributed to the well on pump/yield, equipment and water-quality verification."},
    {topic:"Wastewater and soils",strength:"strong",finding:"SSURGO intersections include rock outcrop, hydrologic C/D soils, slopes and shallow lithic restrictions.",negotiationUse:"Do not pay for cottage/subdivision upside until septic records and site-specific feasibility support the intended density."},
    {topic:"Development upside",strength:"strong",finding:highestBestUse?.recommendedStrategy?.reason||"Highest-and-best-use support remains conditional.",negotiationUse:"Value the property in its verified existing use; treat unapproved subdivision, RV-park or cottage income as speculative upside rather than current value."}
  ];
  const gates=["Current asking price and seller terms","Bedrooms, bathrooms, condition and finish level","Garage and 2,023-SF equipment-building use/finish","Power, HVAC, well equipment/yield/quality and septic permit/capacity","Deed/MLS verification for the primary and secondary sale candidates","Written access/title and zoning confirmations"];
  return {status:sufficient?"preliminary_screening_range":"value_withheld_insufficient_primary_comparables",subjectClass,valuationBoundary:"This is a broker-level acquisition and negotiation screen, not an appraisal, broker price opinion or guarantee of market value.",marketBenchmark:{primaryComparableCount:primary.length,secondaryComparableCount:secondary.length,verifiedSalePriceMedian:money(benchmark),verifiedSalePriceRange:prices.length?[money(Math.min(...prices)),money(Math.max(...prices))]:null,assessorFullCashValue:assessorFcv?money(assessorFcv):null,assessorWarning:"Assessor full cash value is a tax attribute and is not adopted as market value.",conclusion:sufficient?`A preliminary unadjusted sale benchmark is available from ${chosen.length} primary candidates. Apply documented adjustments before recommending a client price.`:`A client-facing value is withheld. ${chosen.length} primary sale candidate(s) do not meet the minimum three-sale evidence gate; the ${money(benchmark)||"unavailable"} median is a benchmark only, not a value conclusion.`},comparableTable,negotiationLeverage:leverage,offerFramework:{askingPrice,openingPosition:"Calculate only after the asking price, property condition and critical due-diligence findings are entered.",ceilingRule:"Do not set a ceiling above a verified adjusted range merely to preserve a deal. Any premium must be attributed to documented improvements, terms or strategic value.",contingencies:["Satisfactory title and legal-access review","Written zoning confirmation","Well performance and water-quality acceptance","Septic record/capacity and site feasibility","Property inspection and improvement verification","Appraisal/financing contingency when applicable"],sellerCreditTargets:["Access or title cure costs","Well testing, repair or equipment deficiencies","Septic investigation, repair or engineered-design costs","Unpermitted improvement or code-correction costs"]},requiredInputs:gates,nextAction:"Collect the asking price and remaining property characteristics, verify sale instruments/MLS records, then rerun targeted market analysis to produce an adjusted offer range and negotiation memo."};
}
