const sources={ar:"https://mohavecounty-az.elaws.us/code/coor_ptii_sec15",setbacks:"https://mohavecounty-az.elaws.us/code/coor_ptii_sec35",adu:"https://www.mohave.gov/news-notices/posts/accessory-residence-requirement-changes/",rvPark:"https://mohavecounty-az.elaws.us/code/coor_ptii_sec37.g",mhPark:"https://mohavecounty-az.elaws.us/code/coor_ptii_sec37.f",rvResidence:"https://www.mohave.gov/departments/development-services/planning-zoning-division/documents/section-37k/",exemption:"https://mohavecounty-az.elaws.us/code/coor_ptii_sec37.y"};

export function resolveZoningRules(parcel:any,overlays:any){
  const zoningResult=overlays?.results?.find((x:any)=>x.id==="zoning");const apn=String(parcel?.attributes?.PARCEL||parcel?.attributes?.TAXPIN||"").replace(/\D/g,"");const feature=(zoningResult?.exactParcelFeatures||zoningResult?.features||[]).find((x:any)=>String(x.TAXPIN||"").replace(/\D/g,"")===apn);const zone=String(feature?.zoning||feature?.rezone_to||"").toUpperCase(),acres=Number(parcel?.attributes?.PARCEL_SIZE||feature?.actual_size||0),combiningMinimum=Number(feature?.min_size||0);if(!feature)return {status:"unresolved",reason:"No exact parcel-matched zoning feature was returned.",sources};const parcelTrs=String(parcel?.attributes?.TWN_RNG_SEC||"").replace(/\s+/g," ").trim(),zoningTrs=[feature.township,feature.range,feature.section].filter(Boolean).join(" "),cadastralConflict=Boolean(parcelTrs&&zoningTrs&&!parcelTrs.includes(String(feature.range||"")));
  if(zone!=="A-R"&&zone!=="AR")return {status:"partial",zone,parcelAcres:acres,reason:"A deterministic rule profile has not yet been encoded for this zone.",sources};
  const theoreticalLots=combiningMinimum>0?Math.floor(acres/combiningMinimum):null;const permitted=["One principal single-family dwelling: site-built, manufactured or qualifying factory-built","Agricultural uses and home occupations","Private gardens, orchards, greenhouses, domestic poultry, horses and cows","Accessory uses normally incidental to a single-family dwelling or light farming"];
  const specialUse=["Recreational-vehicle park","Manufactured-home park","Riding/boarding stable or horse-breeding farm when not agriculturally exempt","Retail plant nursery","Kennel or veterinary clinic","Assisted-living home","Cottage industry"];
  const developmentStandards={baseZoneMinimumLotArea:"1 acre before any larger combining-zone requirement",parcelCombiningMinimum:combiningMinimum?`${combiningMinimum} acres`:"not returned",maximumHeightFeet:35,frontSetbackFeet:15,sideSetbackFeet:5,rearSetbackFeet:15,maximumResidentialLotCoveragePercent:60,structureSeparationFeet:20,notes:["Specific provisions and easements can override general setbacks.","A 10-foot rear setback may apply with a mobile/manufactured home.","No structure may be placed within an easement merely because the zoning setback is met."]};
  const accessoryResidences={currentCountyNoticeDate:"2025-10-21",attachedAllowed:1,detachedAllowed:acres>1?2:1,totalPotentialAccessoryResidences:acres>1?3:2,sizeRule:acres<5?"Each accessory residence generally limited to 75% of primary-residence size absent Special Use Permit approval.":"County notice states the 75% administrative size limit for lots under five acres; confirm Section 37.P permit details for this larger parcel.",setback:"County notice states accessory-structure side and rear setbacks were amended to 5 feet, outside easements.",caution:"Accessory residences do not create separately conveyable lots and remain subject to building, fire, wastewater, access and other applicable codes."};
  const pathways=[
    {use:"Existing/new single-family rural estate with accessory residences",status:"strongest_as_of_right_path",reason:`A-R permits a principal residence, and current county guidance indicates up to ${accessoryResidences.totalPotentialAccessoryResidences} accessory residences on a parcel over one acre.`,requirements:["Confirm current Section 37.P permit interpretation","Demonstrate wastewater capacity for every dwelling","Meet fire access/water and building-code requirements","Keep all structures outside mapped easements"]},
    {use:"Tiny-home or cottage compound under accessory-residence rules",status:"potential_not_automatic",reason:"A limited cottage concept may fit the accessory-residence allowance, but units are not independent lots and tiny-home construction type must meet adopted codes.",requirements:["Planning confirmation of unit count and construction classifications","Site plan","Wastewater design","Fire review","No separate lot sales without land-division approval"]},
    {use:"Conventional subdivision under current A-R/36A zoning",status:theoreticalLots&&theoreticalLots>=2?"potential":"not_supported_by_current_minimum",reason:combiningMinimum?`${acres.toFixed(2)} acres yields only ${theoreticalLots} whole ${combiningMinimum}-acre zoning-sized lot(s) before roads, easements and exclusions.`:"Combining-zone minimum was not returned.",requirements:["Rezone or other entitlement if smaller lots are proposed","Survey and land-division review","Legal and physical access","Water adequacy/availability and wastewater compliance","ADRE applicability review"]},
    {use:"RV park",status:"special_use_permit_path",reason:"A-R allows an RV park only after Special Use Permit approval.",requirements:["Minimum two-acre park area","County-approved wastewater for all spaces and wastewater-producing uses","Internal private-drive and turnaround standards","Building permits for permanent structures","Fire and access review"]},
    {use:"Manufactured-home park",status:"special_use_permit_path",reason:"A-R allows a manufactured-home park only after Special Use Permit approval.",requirements:["Minimum three-acre park parcel","Approved wastewater system","Internal streets and space standards","Two parking spaces per home","County and state installation/building compliance"]}
  ];
  return {status:"parcel_matched",zone:"A-R",combiningZone:feature.rezone_to||feature.ZONE_KEY||null,parcelAcres:acres,generalPlan:overlays?.conclusions?.find((x:any)=>x.topic==="general_plan")?.evidence?.LandUse||null,sourceDiagnostics:{exactApnMatch:true,parcelTownshipRangeSection:parcelTrs||null,zoningRecordTownshipRangeSection:zoningTrs||null,cadastralConflict,interpretation:cadastralConflict?"The exact-APN zoning polygon supports the zoning conclusion, but its township/range/section attributes conflict with the parcel/legal record. Obtain written Planning confirmation before relying on the historical rezone resolution or entitlement history.":"No township/range/section conflict detected between returned parcel and zoning attributes."},permittedUses:permitted,specialUsePermitUses:specialUse,developmentStandards,accessoryResidences,pathways,sources,neededConfirmation:cadastralConflict?{agency:"Mohave County Planning & Zoning",request:`Confirm current zoning and applicable rezone resolution for APN ${parcel?.attributes?.PARCEL||parcel?.attributes?.TAXPIN}; explain why the zoning layer returns ${zoningTrs} while the parcel/legal record returns ${parcelTrs}.`,contact:"planners@mohave.gov / (928) 757-0903",return:"Written zoning confirmation and controlling resolution or case number"}:null,conclusion:"Current zoning most strongly supports a rural residential estate with agricultural/accessory uses and a limited accessory-residence or cottage-compound strategy. A conventional multi-lot subdivision is not supported by the 36-acre combining minimum on a 38.21-acre parcel without entitlement changes."};
}
