import type { PropertyReport,ReportSection,Source } from "../../lib/report";
import { resolveMohaveParcel } from "../../lib/parcel-resolver";
import { resolveSpatialOverlays } from "../../lib/spatial-overlays";
import { resolveAdwrWells } from "../../lib/adwr-wells";
import { resolveUsdaSoils } from "../../lib/usda-soils";
import { resolveRecorderLeads } from "../../lib/recorder-leads";
import { resolveMarketComps } from "../../lib/market-comps";
import { resolveBuildingDetails } from "../../lib/building-details";
import { resolveZoningRules } from "../../lib/zoning-rules";
import { resolveLandDivisionRules } from "../../lib/land-division-rules";
import { resolveValuationNegotiation } from "../../lib/valuation-negotiation";
import { buildEvidencePackage } from "../../lib/evidence-package";
import { getSupabaseAdmin } from "../../lib/supabase-admin";
export const maxDuration=300;

const titles:Record<string,string>={parcel:"Property identity",title:"Recorder and title",zoning:"Zoning and ordinances",access:"Access and right-of-way",flood:"Flood screening",water:"Wells and water",septic:"Septic and soils",utilities:"Utilities",fire:"Fire service and code",environment:"Environmental",market:"Comparable value",negotiation:"Negotiation strategy"};
const official=(title:string,url:string):Source=>({title,url,authority:"Official",accessed:new Date().toISOString().slice(0,10)});
const section=(id:string,status:ReportSection["status"],summary:string,findings:string[]=[],risks:string[]=[],actions:string[]=[],sources:Source[]=[]):ReportSection=>({id,title:titles[id],status,summary,findings,risks,actions,sources});
const compactApn=(value:unknown)=>String(value||"").replace(/\D/g,"");
const money=(value:unknown)=>Number(value)>0?new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(Number(value)):"Not returned";
function overlay(data:any,topic:string){return data?.conclusions?.find((x:any)=>x.topic===topic)}
async function timed(label:string,promise:Promise<any>,fallback:any,ms=20000):Promise<any>{let timer:ReturnType<typeof setTimeout>|undefined;try{return await Promise.race([promise,new Promise<any>(resolve=>{timer=setTimeout(()=>resolve({...fallback,status:"temporarily_unavailable",error:`${label} exceeded ${Math.round(ms/1000)} seconds and was deferred.`}),ms)})])}finally{if(timer)clearTimeout(timer)}}

export async function POST(request:Request){
 try{
  const body=await request.json();const digits=compactApn(body.apn);if(digits.length!==8)return Response.json({ok:false,error:"Enter a valid Mohave County APN."},{status:400});
  const apn=`${digits.slice(0,3)}-${digits.slice(3,5)}-${digits.slice(5)}`;const modules=Array.isArray(body.researchModules)?body.researchModules.map(String):["parcel","zoning","access","flood","market"];const caseId=String(body.caseId||"");
  const parcel=await resolveMohaveParcel(apn);if(parcel?.status!=="resolved")return Response.json({ok:false,error:"Mohave County parcel data did not return an exact APN match."},{status:404});
  const parcelApn=String(parcel.attributes?.PARCEL||parcel.attributes?.TAXPIN||apn);
  const [spatial,buildings,market,wells,soils]=await Promise.all([
   timed("Mohave spatial layers",resolveSpatialOverlays(parcel),{status:"temporarily_unavailable",results:[],conclusions:[]}),timed("Assessor improvements",resolveBuildingDetails([parcelApn]),{status:"temporarily_unavailable",parcels:{},diagnostics:[]},12000),modules.includes("market")?timed("Comparable-sale search",resolveMarketComps(parcel),{status:"temporarily_unavailable",groups:{},derived:{primaryComparableCount:0,secondaryComparableCount:0}},18000):null,modules.includes("water")?timed("ADWR well search",resolveAdwrWells(parcel),{status:"temporarily_unavailable",onParcel:[],nearby:[]},15000):null,modules.some((x:string)=>["septic","environment"].includes(x))?timed("USDA soil search",resolveUsdaSoils(parcel),{status:"temporarily_unavailable",mapUnits:[],components:[],septicInterpretations:[]},18000):null
  ]);
  const zoningRules=modules.some((x:string)=>["zoning","access","fire","utilities"].includes(x))?resolveZoningRules(parcel,spatial):null;
  const landDivisionRules=modules.includes("zoning")&&zoningRules?resolveLandDivisionRules(parcel,zoningRules):null;
  const recorder=modules.includes("title")?await timed("Recorder and survey leads",resolveRecorderLeads(parcel,spatial),{status:"temporarily_unavailable",leads:[],surveys:[],conclusions:[]},15000):null;
  const valuation=modules.includes("market")?resolveValuationNegotiation(parcel,market,null,String(body.knownInformation||"")):null;
  const direct={county:parcel,buildings,spatial,zoningRules,landDivisionRules,highestBestUse:null,valuationNegotiation:valuation,recorder,market,wells,soils};
  const evidencePackage=buildEvidencePackage([{kind:"parcel",directEvidence:direct},{kind:"recorder",directEvidence:direct},{kind:"water",directEvidence:direct},{kind:"zoning",directEvidence:direct}]);
  const attrs=parcel.attributes||{},zoning=overlay(spatial,"zoning"),plan=overlay(spatial,"general_plan"),row=overlay(spatial,"right_of_way"),abandon=overlay(spatial,"right_of_way_abandonment"),roads=overlay(spatial,"road_adjacency"),maintenance=overlay(spatial,"county_maintenance"),flood=overlay(spatial,"flood");
  const parcelSource=official("Mohave County parcel GIS",`${parcel.service}/${parcel.layer}`),gisSource=official("Mohave County GIS layers","https://mcgis.mohave.gov/arcgis/rest/services"),femaSource=official("FEMA National Flood Hazard Layer","https://hazards.fema.gov/arcgis/rest/services/public/NFHL/MapServer/28"),adwrSource=official("Arizona Department of Water Resources Well Registry",wells?.source||"https://azwatermaps.azwater.gov/wellreg");
  const building=Object.values(buildings?.parcels||{})[0] as any;const improvements=(building?.improvements||[]).map((x:any)=>`${x.description||"Improvement"}${x.squareFeet?` — ${x.squareFeet} SF`:""}${x.yearBuilt?`, built ${x.yearBuilt}`:""}`);
  const primaryCount=Number(market?.derived?.primaryComparableCount||0),secondaryCount=Number(market?.derived?.secondaryComparableCount||0),benchmark=valuation?.marketBenchmark;
  const sections:ReportSection[]=[
   section("parcel","Verified",`Exact Mohave County APN match for ${parcelApn}.`,[`Site address: ${attrs.SITE_ADDRESS||"No situs address returned"}`,`Owner shown: ${attrs.OWNER||"Not returned"}`,`Parcel size: ${attrs.PARCEL_SIZE||"Not returned"} ${attrs.UNIT_TYPE||""}`,`Legal description: ${attrs.LEGAL_DESCRIPTION||"Not returned"}`,`Assessor full cash value: ${money(attrs.FULL_CASH_VALUE)}`,...improvements],[],[],[parcelSource]),
   modules.includes("title")?section("title",recorder?.leads?.length?"Partially verified":"Unverified",recorder?.conclusions?.join(" ")||"No recorder leads were derived.",(recorder?.leads||[]).map((x:any)=>`${x.referenceType}: ${x.reference} — ${x.role}`),["Recorder leads are not a title examination."],recorder?.humanCheckpoint?.required?recorder.humanCheckpoint.steps:[],[official("Mohave County Recorder public records","https://eaglerss.mohave.gov/web/")]):section("title","Not applicable","Recorder depth was outside the selected scope."),
   section("zoning",zoning?"Verified":"Unverified",zoning?.statement||"No exact parcel-matched zoning conclusion returned.",[zoningRules?.conclusion,plan?.statement,landDivisionRules?.subjectConclusion].filter(Boolean),zoningRules?.sourceDiagnostics?.cadastralConflict?[zoningRules.sourceDiagnostics.interpretation]:[],zoningRules?.neededConfirmation?[zoningRules.neededConfirmation.request]:[],[gisSource,...Object.entries(zoningRules?.sources||{}).map(([key,url])=>official(`Mohave zoning source: ${key}`,String(url)))]),
   section("access",row||roads?"Partially verified":"Unverified",[row?.statement,roads?.statement,maintenance?.statement].filter(Boolean).join(" ")||"No mapped road or right-of-way conclusion returned.",[],abandon?[abandon.statement,"GIS intersection does not establish legal access."]:[],["Compare mapped roads and recorded instruments against title evidence and survey."],[gisSource]),
   section("flood",flood?"Verified":"Unverified",flood?.statement||"FEMA NFHL intersection returned no mapped feature.",[],["Flood mapping is a screening result and not an elevation certificate or drainage study."],[],[femaSource]),
   modules.includes("water")?section("water",wells?.onParcel?.length?"Partially verified":"Unverified",wells?.onParcel?.length?`${wells.onParcel.length} ADWR registry point(s) matched the parcel polygon.`:"No on-parcel ADWR registry point was returned.",(wells?.onParcel||[]).map((x:any)=>`${x.registrationNumber}: depth ${x.WELL_DEPTH??"unknown"} ft; water level ${x.WATER_LEVEL??"unknown"} ft; casing ${x.CASING_DEPTH??"unknown"} ft.`),["Registry location and driller-reported construction do not prove current yield, quality or operability."],wells?.onParcel?.length?["Open the linked Well 55 record and obtain the drill log, pump/yield test and water-quality results."]:[],[adwrSource]):section("water","Not applicable","Water research was outside the selected scope."),
   modules.includes("septic")?section("septic",soils?.mapUnits?.length?"Partially verified":"Unverified",soils?.derived?.conclusion||"No SSURGO septic interpretation returned.",(soils?.mapUnits||[]).map((x:any)=>`${x.musym}: ${x.muname}`),soils?.disclaimer?[String(soils.disclaimer)]:[],["Obtain the County septic permit record when improvements or development plans make it material."],[official("USDA NRCS Soil Data Access",soils?.source||"https://sdmdataaccess.sc.egov.usda.gov/")]):section("septic","Not applicable","Septic and soils were outside the selected scope."),
   modules.includes("utilities")?section("utilities","Unverified","No authoritative parcel-specific utility service boundary connector is currently installed.",[],[],["Verify electric and communications providers only when material to the client objective."]):section("utilities","Not applicable","Utilities were outside the selected scope."),
   modules.includes("fire")?section("fire","Unverified","Fire service remains user-supplied until a parcel-specific district boundary is connected.",[],[],[String(body.fireService||"").startsWith("Unknown")?"Identify the serving fire district from a district boundary or written confirmation.":`Confirm service with ${String(body.fireService)}.`]):section("fire","Not applicable","Fire research was outside the selected scope."),
   modules.includes("environment")?section("environment",soils?.mapUnits?.length?"Partially verified":"Unverified","Environmental screening currently contains FEMA and SSURGO public layers; no Phase I environmental assessment was performed.",[],[],[],[femaSource,official("USDA NRCS Soil Data Access",soils?.source||"https://sdmdataaccess.sc.egov.usda.gov/")]):section("environment","Not applicable","Environmental screening was outside the selected scope."),
   section("market",market?.status==="queried"?"Partially verified":"Unverified",benchmark?.conclusion||market?.derived?.conclusion||"No assessor-sale comparison was returned.",[`Search ladder: ${(market?.searchLadder||[]).map((x:any)=>`${x.radiusMiles} mi/${x.lookbackYears} yr`).join(" → ")||"Not returned"}`,`Primary candidates: ${primaryCount}; secondary candidates: ${secondaryCount}`,`Assessor FCV: ${money(attrs.FULL_CASH_VALUE)}`,`Unadjusted verified-sale median: ${benchmark?.verifiedSalePriceMedian||"Withheld"}`],primaryCount<3?["Fewer than three qualifying primary sales; no client-facing value conclusion is supported."]:[],["Connect the authorized WARDEX/RESO feed to verify closed-sale condition, concessions, photos and listing history."],[official("Mohave County Assessor sale attributes",market?.source||"https://mcgis.mohave.gov/arcgis/rest/services/PARCELS/MapServer/14")]),
   modules.includes("negotiation")?section("negotiation",valuation?"Partially verified":"Unverified",valuation?.nextAction||"Negotiation analysis requires verified market and deal inputs.",(valuation?.negotiationLeverage||[]).map((x:any)=>`${x.topic}: ${x.finding}`),[],valuation?.offerFramework?.contingencies||[]):section("negotiation","Not applicable","Negotiation analysis was outside the selected scope.")
  ];
  const neededItems=[] as PropertyReport["neededItems"];
  if(recorder?.humanCheckpoint?.required)neededItems.push({priority:"Important",item:"Recorder document images",why:"Prepared fee-number leads require the County portal’s human CAPTCHA checkpoint.",provide:`Download and upload the matching instruments for: ${(recorder.leads||[]).filter((x:any)=>x.retrieval==="recorder_checkpoint").map((x:any)=>x.reference).join(", ")}.`});
  if(modules.includes("market")&&primaryCount<3)neededItems.push({priority:"Important",item:"Authorized MLS comparable verification",why:"Assessor sales alone do not establish condition, concessions or listing history.",provide:"Connect the agent-authorized WARDEX/RESO feed or add verified MLS sheets for appropriate closed sales."});
  const verifiedFacts=sections.filter(x=>x.status==="Verified").flatMap(x=>x.findings.slice(0,3));const criticalRisks=sections.flatMap(x=>x.risks).slice(0,8);
  const report:PropertyReport={apn:parcelApn,generatedAt:new Date().toISOString(),overallConfidence:sections.filter(x=>x.status==="Verified").length>=3?"Moderate":"Low",decision:"Public-source property screen completed; professional review required for transaction reliance.",executiveSummary:`The zero-AI public-data collector resolved APN ${parcelApn} and completed the selected county, GIS and technical-source queries. ${primaryCount>=3?"A preliminary assessor-sale comparison set is available.":"Comparable value remains withheld until an authorized MLS feed or sufficient verified primary sales are available."}`,verifiedFacts,criticalRisks,useRanking:[],sections,neededItems,dueDiligence:[{timing:"Before offer or during inspection period",task:"Review title, legal access, zoning, water, wastewater and material map conflicts.",owner:"Real estate professional / buyer"},{timing:"Before client delivery",task:"Review every source link, qualification and unresolved item.",owner:"Responsible real estate professional"}],limitations:["This automated public-source screen is not an appraisal, title opinion, survey, zoning clearance, permit approval, engineering report or guarantee.","No OpenAI model or paid web-search tool was used to generate this report.","Public-source data may be incomplete, delayed or inaccurate and requires professional review."],evidencePackage};
  const db=getSupabaseAdmin();if(db&&caseId){const prior=await db.from("report_versions").select("version_number").eq("case_id",caseId).order("version_number",{ascending:false}).limit(1);const version=(prior.data?.[0]?.version_number||0)+1;await db.from("report_versions").insert({case_id:caseId,version_number:version,report_type:"public_data",included_sections:sections.map(x=>x.id),report_data:report,approval_status:"draft"});if(neededItems.length)await db.from("action_requests").insert(neededItems.map(item=>({case_id:caseId,priority:item.priority.toLowerCase(),title:item.item,question:item.why,reason:item.why,requested_return:item.provide,status:"open"})));await db.from("cases").update({status:neededItems.length?"waiting_for_input":"professional_review",confidence:report.overallConfidence.toLowerCase(),readiness:Math.max(35,90-neededItems.length*10)}).eq("id",caseId)}
  return Response.json({ok:true,report,costMode:"public_data_only",aiCalls:0});
 }catch(error){console.error("Public assessment failed",error);return Response.json({ok:false,error:error instanceof Error?error.message:"Public assessment failed."},{status:500})}
}
