"use client";
import { useState } from "react";
import { ResearchScopeSelector } from "./research-scope";
type Candidate={apn:string;address:string;owner:string;acres:number|null;unit:string;useCode:string;propertyCode:string;fullCashValue:number|null;latitude:number|null;longitude:number|null};
export function NewPropertyWizard({apn,onApn,objective,onObjective,knownInformation,onKnownInformation,propertyTypes,onPropertyTypes,propertyOptions,purpose,onPurpose,researchModules,onResearchModules,fireService,onFireService,fireOptions,running,status,onFile,onRun}:{apn:string;onApn:(v:string)=>void;objective:string;onObjective:(v:string)=>void;knownInformation:string;onKnownInformation:(v:string)=>void;propertyTypes:string[];onPropertyTypes:(v:string[])=>void;propertyOptions:string[];purpose:string;onPurpose:(v:string)=>void;researchModules:string[];onResearchModules:(v:string[])=>void;fireService:string;onFireService:(v:string)=>void;fireOptions:string[];running:boolean;status:string;onFile:(file?:File)=>void;onRun:()=>void}){
 const[step,setStep]=useState(1),[type,setType]=useState("apn"),[value,setValue]=useState(""),[verification,setVerification]=useState(""),[mls,setMls]=useState(""),[candidates,setCandidates]=useState<Candidate[]>([]),[selected,setSelected]=useState<Candidate|null>(null),[lookup,setLookup]=useState(""),[busy,setBusy]=useState(false);
 async function find(){const searchType=type==="mls"?(verification.replace(/\D/g,"").length===8?"apn":"address"):type;const searchValue=type==="mls"?verification:value;if(type==="mls"&&!mls.trim()){setLookup("Enter the MLS number.");return}setBusy(true);setLookup("Checking Mohave County GIS…");try{const response=await fetch("/api/parcel/resolve?type="+encodeURIComponent(searchType)+"&value="+encodeURIComponent(searchValue));const data=await response.json();if(!response.ok||!data.ok)throw new Error(data.error||"Property could not be resolved.");setCandidates(data.candidates||[]);if(data.candidates?.length===1)choose(data.candidates[0]);else{setStep(2);setLookup(data.candidates.length+" candidate parcels returned. Select the subject property.")}}catch(error){setLookup(error instanceof Error?error.message:"Property lookup failed.")}finally{setBusy(false)}}
 function choose(item:Candidate){setSelected(item);onApn(item.apn);if(mls.trim())onKnownInformation((knownInformation+"\nMLS NUMBER: "+mls.trim()).trim());setStep(2);setLookup("County parcel candidate selected. Confirm it before configuring research.")}
 return <section className="newPropertyWizard"><div className="wizardHeading"><p className="eyebrow">NEW PROPERTY</p><h2>Identify, confirm and research</h2><p>Start with whatever the Realtor has. The county parcel is confirmed before deeper research begins.</p></div><ol className="wizardSteps">{["Identify","Confirm","Purpose","Review"].map((x,i)=><li className={step===i+1?"active":step>i+1?"done":""} key={x}><b>{i+1}</b><span>{x}</span></li>)}</ol>
 {step===1&&<div className="wizardPanel"><h3>How are you identifying the property?</h3><div className="identifierTypes">{[["apn","APN"],["address","Address"],["coordinates","Coordinates"],["mls","MLS number"]].map(([id,label])=><button type="button" className={type===id?"active":""} key={id} onClick={()=>setType(id)}>{label}</button>)}</div>{type==="mls"?<><label>MLS number<input value={mls} onChange={e=>setMls(e.target.value)} placeholder="WARDEX/Momentum MLS number"/></label><label>APN or address for county verification<input value={verification} onChange={e=>setVerification(e.target.value)} placeholder="Required until the authorized MLS API is connected"/></label><small>The MLS number is preserved with the case; county identity is confirmed independently.</small></>:<label>{type==="apn"?"Mohave County APN":type==="address"?"Property address":"Latitude, longitude"}<input value={value} onChange={e=>setValue(e.target.value)} placeholder={type==="apn"?"353-15-018":type==="address"?"3060 N Boulder Pass":"35.212528, -113.386724"}/></label>}<button type="button" disabled={busy} onClick={()=>void find()}>{busy?"Checking property…":"Find property"}</button><small>{lookup||"No full research is run during this confirmation step."}</small></div>}
 {step===2&&<div className="wizardPanel"><h3>Confirm the subject property</h3>{!selected&&candidates.length>1?<div className="candidateList">{candidates.map(x=><button type="button" key={x.apn} onClick={()=>choose(x)}><b>{x.apn}</b><span>{x.address||"No site address returned"}</span><small>{x.owner+" · "+(x.acres||"—")+" "+x.unit}</small></button>)}</div>:selected?<div className="subjectConfirm"><img src={"/api/exhibits/diagram?type=parcel&apn="+encodeURIComponent(selected.apn)} alt="Parcel confirmation diagram"/><div><p className="eyebrow">COUNTY CANDIDATE</p><h3>{selected.address||"APN "+selected.apn}</h3><dl><div><dt>APN</dt><dd>{selected.apn}</dd></div><div><dt>Owner</dt><dd>{selected.owner||"Not returned"}</dd></div><div><dt>Size</dt><dd>{selected.acres??"—"} {selected.unit}</dd></div><div><dt>Classification</dt><dd>{selected.propertyCode||selected.useCode||"Not returned"}</dd></div><div><dt>Assessor value</dt><dd>{selected.fullCashValue?selected.fullCashValue.toLocaleString("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}):"Not returned"}</dd></div></dl></div></div>:null}<div className="wizardButtons"><button type="button" className="secondary" onClick={()=>{setSelected(null);setCandidates([]);setStep(1)}}>Wrong property</button><button type="button" disabled={!selected} onClick={()=>setStep(3)}>Confirm subject</button></div><small>{lookup}</small></div>}
 {step===3&&<div className="wizardPanel"><h3>What is the Realtor doing?</h3><ResearchScopeSelector purpose={purpose} modules={researchModules} onPurpose={onPurpose} onModules={onResearchModules}/><fieldset><legend>Property categories — select all that apply</legend><div className="checks">{propertyOptions.map(x=><label className="check" key={x}><input type="checkbox" checked={propertyTypes.includes(x)} onChange={e=>onPropertyTypes(e.target.checked?[...propertyTypes,x]:propertyTypes.filter(v=>v!==x))}/><span>{x}</span></label>)}</div></fieldset><label>Client objective<textarea value={objective} onChange={e=>onObjective(e.target.value)} placeholder="Purchase inquiry, listing preparation, cottage community, resale…"/></label><label>Known or suspected fire service<select value={fireService} onChange={e=>onFireService(e.target.value)}>{fireOptions.map(x=><option key={x}>{x}</option>)}</select></label><div className="wizardButtons"><button type="button" className="secondary" onClick={()=>setStep(2)}>Back</button><button type="button" disabled={!propertyTypes.length} onClick={()=>setStep(4)}>Review scope</button></div></div>}
 {step===4&&<div className="wizardPanel"><h3>Review before research</h3><div className="reviewGrid"><div><small>Property</small><b>{selected?.address||apn}</b><span>{"APN "+apn+(mls?" · MLS "+mls:"")}</span></div><div><small>Purpose</small><b>{purpose}</b><span>{propertyTypes.join(" · ")}</span></div><div><small>Research</small><b>{researchModules.length} modules</b><span>{researchModules.join(" · ")}</span></div></div><label>Known facts or pasted document text<textarea value={knownInformation} onChange={e=>onKnownInformation(e.target.value)} placeholder="Seller claims, MLS facts, well number, title notes…"/></label><label className="fileLabel">Add supporting text file<input type="file" accept=".txt,.md,.csv,.json" onChange={e=>onFile(e.target.files?.[0])}/></label><div className="wizardButtons"><button type="button" className="secondary" onClick={()=>setStep(3)}>Adjust scope</button><button type="button" disabled={running||!apn||!propertyTypes.length} onClick={onRun}>{running?"Researching…":"Start property research"}</button></div><small role="status">{status}</small></div>}
 </section>
}
