"use client";
import { FormEvent, useMemo, useRef, useState } from "react";
import type { PropertyReport, ReportSection } from "./lib/report";

type ApiResult={ok:boolean;report?:PropertyReport;error?:string};
const protocol=["Parcel","Title","Zoning","Access","Flood","Water","Septic","Utilities","Fire","Environment","Market & Use","Negotiation"];
const propertyOptions=["Residential","Vacant Land","Commercial","Large Acreage / Subdivision"];
const fireOptions=["Unknown — research needed","Pinion Pine Fire District","Golden Valley Fire District","Northern Arizona Consolidated Fire District","Yucca Fire District","Desert Hills Fire District","Mohave Valley Fire District","Fort Mojave Mesa Fire District","Lake Havasu City Fire Department","Kingman Fire Department","Bullhead City Fire Department","Other / user supplied"];

function List({title,items,tone=""}:{title:string;items:string[];tone?:string}){if(!items.length)return null;return <div className={`listBlock ${tone}`}><h4>{title}</h4><ul>{items.map((x,i)=><li key={i}>{x}</li>)}</ul></div>}
function SectionView({section}:{section:ReportSection}){return <article className="sectionView"><div className="sectionTitle"><div><p className="eyebrow">REPORT FIELD</p><h2>{section.title}</h2></div><span className={`badge ${section.status.replaceAll(" ","").toLowerCase()}`}>{section.status}</span></div><p className="lead">{section.summary}</p><div className="twoCol"><List title="Findings" items={section.findings}/><List title="Risk flags" items={section.risks} tone="risk"/><List title="Recommended actions" items={section.actions} tone="action"/><div className="listBlock"><h4>Evidence register</h4>{section.sources.length?section.sources.map((s,i)=><p className="source" key={i}><b>{s.authority}</b> · <a href={s.url} target="_blank" rel="noreferrer">{s.title}</a><small>Accessed {s.accessed}</small></p>):<p>No directly matched source recorded.</p>}</div></div></article>}

export default function Home(){
 const[apn,setApn]=useState("");const[objective,setObjective]=useState("");const[knownInformation,setKnownInformation]=useState("");const[propertyTypes,setPropertyTypes]=useState<string[]>([]);const[fireService,setFireService]=useState(fireOptions[0]);const[status,setStatus]=useState("Ready for a Mohave County parcel.");const[report,setReport]=useState<PropertyReport|null>(null);const[caseId,setCaseId]=useState("");const[running,setRunning]=useState(false);const[tab,setTab]=useState("overview");const[answers,setAnswers]=useState<Record<number,string>>({});const[selectedSections,setSelectedSections]=useState<string[]>([]);const[finalReady,setFinalReady]=useState(false);
 const validApn=useMemo(()=>apn.replace(/\D/g,"").length===8,[apn]);const caseIdRef=useRef("");
 async function postAnalysis(payload:Record<string,unknown>){if(payload.action==="investigate"&&!caseIdRef.current){const created=await fetch("/api/cases",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({apn,objective,propertyTypes,fireService})});const saved=await created.json();if(!created.ok||!saved.ok)throw new Error(saved.error||"Could not save the property case.");caseIdRef.current=saved.case.id;setCaseId(saved.case.id)}const response=await fetch("/api/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({apn,objective,knownInformation,propertyTypes,fireService,caseId:caseIdRef.current,...payload})});const raw=await response.text();let data:any;try{data=JSON.parse(raw)}catch{throw new Error(`A research stage stopped before completing (${response.status}).`)}if(!response.ok||!data.ok)throw new Error(data.error||"A research stage failed.");return data}
 async function waitForJob(responseId:string,jobType:"investigation"|"synthesis",jobId?:string){for(let attempt=0;attempt<160;attempt++){await new Promise(resolve=>setTimeout(resolve,3000));const data=await postAnalysis({action:"poll",responseId,jobType,jobId});if(data.status==="completed")return data}throw new Error("The background research exceeded eight minutes. Retry or inspect the OpenAI project logs.")}
 async function runInvestigator(kind:string,stage:number){const delays=[5000,15000,30000];for(let attempt=0;attempt<=delays.length;attempt++){setStatus(`Research stage ${stage} of 5: ${kind} investigator is working${attempt?` — retry ${attempt}`:""}…`);try{const start=await postAnalysis({action:"investigate",kind});const result=await waitForJob(start.responseId,"investigation",start.jobId);return {kind:start.kind,notes:result.notes,directEvidence:start.directEvidence}}catch(error){const message=error instanceof Error?error.message:"failed";if(!message.includes("rate_limit_exceeded")||attempt===delays.length)throw error;setStatus(`${kind.toUpperCase()} reached the temporary token limit. Completed work is safe; retrying in ${delays[attempt]/1000} seconds…`);await new Promise(resolve=>setTimeout(resolve,delays[attempt]))}}}
 async function run(event?:FormEvent){event?.preventDefault();if(!validApn){setStatus("Enter an eight-digit Mohave County APN, such as 353-15-018.");return}if(!propertyTypes.length){setStatus("Select at least one property-analysis category.");return}setRunning(true);setReport(null);setFinalReady(false);try{const kinds=["parcel","recorder","water","zoning"];const completed:any[]=[];for(let i=0;i<kinds.length;i++){try{completed.push(await runInvestigator(kinds[i],i+1));if(i<kinds.length-1)await new Promise(resolve=>setTimeout(resolve,4000))}catch(error){throw new Error(`${kinds[i].toUpperCase()} investigator: ${error instanceof Error?error.message:"failed"}`)}}setStatus("Research stage 5 of 5: reconciling evidence and generating report fields…");let data:ApiResult|undefined;for(let attempt=0;attempt<4;attempt++){try{const synthesis=await postAnalysis({action:"synthesize",investigations:completed});data=await waitForJob(synthesis.responseId,"synthesis");break}catch(error){const message=error instanceof Error?error.message:"failed";if(!message.includes("rate_limit_exceeded")||attempt===3)throw error;const delay=[5000,15000,30000][attempt];setStatus(`Synthesis reached the temporary token limit. Retrying in ${delay/1000} seconds…`);await new Promise(resolve=>setTimeout(resolve,delay))}}if(!data?.report)throw new Error("No report returned.");setReport(data.report);setSelectedSections(data.report.sections.map(s=>s.id));setTab("overview");setStatus(`Analysis completed with ${data.report.overallConfidence.toLowerCase()} confidence. Resolve requested information before generating the client report.`)}catch(error){setStatus(error instanceof Error?error.message:"Analysis failed.")}finally{setRunning(false)}}
 async function loadTextFile(file?:File){if(!file)return;if(file.size>500_000){setStatus("That text file is too large; keep supporting text under 500 KB.");return}const text=await file.text();setKnownInformation(v=>`${v}\n\nUPLOADED ${file.name}:\n${text}`.trim());setStatus(`${file.name} added to supporting information.`)}
 function applyAnswers(){if(!report)return;const added=report.neededItems.map((item,i)=>answers[i]?.trim()?`${item.item}: ${answers[i].trim()}`:"").filter(Boolean).join("\n");if(!added){setStatus("Enter at least one requested answer first.");return}setKnownInformation(v=>`${v}\n${added}`.trim());setStatus("Answers added. Run the analysis again to incorporate and verify them.")}
 const tabs=report?[{id:"overview",label:"Decision Summary"},{id:"needed",label:`Needed Information (${report.neededItems.length})`},...report.sections.map(s=>({id:s.id,label:s.title})),{id:"final",label:"Polished Report"}]:[];
 return <main><header><p>DIRT ROAD</p><h1>Property Analyzer & Transaction Coordinator</h1><span>Mohave County, Arizona</span></header>
 <section className="hero"><div><p className="eyebrow">ACQUISITION INTELLIGENCE</p><h2>Evidence first. Conclusions second.</h2><p>The analyzer follows a defined source ladder, identifies unresolved facts and separates each due-diligence discipline into its own report field.</p><div className="protocol">{protocol.map((x,i)=><span key={x}><b>{i+1}</b>{x}</span>)}</div></div><form onSubmit={run}><label>Mohave County APN<input value={apn} onChange={e=>setApn(e.target.value)} placeholder="353-15-018" disabled={running}/></label><fieldset><legend>Property analysis categories — select all that apply</legend><div className="checks">{propertyOptions.map(x=><label className="check" key={x}><input type="checkbox" checked={propertyTypes.includes(x)} onChange={e=>setPropertyTypes(e.target.checked?[...propertyTypes,x]:propertyTypes.filter(v=>v!==x))}/><span>{x}</span></label>)}</div></fieldset><label>Known or suspected fire service<select value={fireService} onChange={e=>setFireService(e.target.value)}>{fireOptions.map(x=><option key={x}>{x}</option>)}</select><small>Selecting a department is user-supplied until verified against the parcel/district layer.</small></label><label>Buyer objective<textarea value={objective} onChange={e=>setObjective(e.target.value)} placeholder="Tiny-home community, resale, ranch, subdivision…" disabled={running}/></label><label>Known facts or pasted document text<textarea value={knownInformation} onChange={e=>setKnownInformation(e.target.value)} placeholder="Seller claims, well number, zoning response, title notes…" disabled={running}/></label><label className="fileLabel">Add supporting text file<input type="file" accept=".txt,.md,.csv,.json" onChange={e=>loadTextFile(e.target.files?.[0])} disabled={running}/><small>Text files are incorporated now. PDF/image extraction remains a connector build.</small></label><button disabled={running}>{running?"Researching every field…":"Run full assessment"}</button><small role="status">{status}</small></form></section>
 {report&&<section className="workspace"><nav className="tabs" aria-label="Report sections">{tabs.map(t=><button type="button" key={t.id} className={tab===t.id?"active":""} onClick={()=>setTab(t.id)}>{t.label}</button>)}</nav><div className="tabPanel">
 {tab==="overview"&&<article><div className="reportHero"><div><p className="eyebrow">ACQUISITION DECISION</p><h2>APN {report.apn}</h2><p>{report.executiveSummary}</p></div><div className="decision"><small>Current conclusion</small><strong>{report.decision}</strong><span>{report.overallConfidence} confidence</span></div></div><div className="twoCol"><List title="Verified parcel facts" items={report.verifiedFacts}/><List title="Critical unresolved risks" items={report.criticalRisks} tone="risk"/><div className="listBlock wide"><h4>Highest-and-best-use ranking</h4>{report.useRanking.sort((a,b)=>a.rank-b.rank).map(x=><div className="useRow" key={x.rank}><b>#{x.rank}</b><div><strong>{x.use}</strong><p>{x.viability}</p><small>{x.conditions.join(" · ")}</small></div></div>)}</div></div></article>}
 {tab==="needed"&&<article><p className="eyebrow">COMPLETENESS GATE</p><h2>Information needed to strengthen this report</h2><p className="lead">Provide only what is available. Each answer is added to the next research pass; supplied information remains labeled until independently verified.</p><div className="neededGrid">{report.neededItems.map((x,i)=><div className="needed" key={i}><span className={`priority ${x.priority.toLowerCase()}`}>{x.priority}</span><h3>{x.item}</h3><p>{x.why}</p><small>Provide: {x.provide}</small><textarea placeholder="Type the answer, document reference, or professional response…" value={answers[i]||""} onChange={e=>setAnswers({...answers,[i]:e.target.value})}/></div>)}</div><button type="button" onClick={applyAnswers}>Add answers for next analysis</button></article>}
 {report.sections.map(s=>tab===s.id?<SectionView key={s.id} section={s}/>:null)}
 {tab==="final"&&<article><div className="finalControls"><p className="eyebrow">CLIENT REPORT BUILDER</p><h2>Select the sections to include</h2><p>Internal research remains available in its tabs. Only checked sections appear in the client-facing report.</p><div className="reportChecks">{report.sections.map(s=><label className="check" key={s.id}><input type="checkbox" checked={selectedSections.includes(s.id)} onChange={e=>{setFinalReady(false);setSelectedSections(e.target.checked?[...selectedSections,s.id]:selectedSections.filter(id=>id!==s.id))}}/><span>{s.title}</span></label>)}</div><button type="button" onClick={()=>{if(!selectedSections.length){setStatus("Select at least one final-report section.");return}setFinalReady(true);setStatus("Final report generated from the selected sections.")}}>Generate final report</button></div>{finalReady&&<div className="printReport"><div className="printCover"><p>DIRT ROAD PROPERTY ANALYZER</p><h1>Property Acquisition Assessment</h1><h2>Mohave County APN {report.apn}</h2><span>Prepared {new Date(report.generatedAt).toLocaleDateString()}</span></div><section><h2>Executive decision</h2><p>{report.executiveSummary}</p><div className="callout"><b>{report.decision}</b><span>{report.overallConfidence} overall confidence</span></div></section>{report.sections.filter(s=>selectedSections.includes(s.id)).map(s=><section key={s.id}><h2>{s.title}</h2><p>{s.summary}</p><List title="Findings" items={s.findings}/><List title="Risks" items={s.risks}/><List title="Recommended actions" items={s.actions}/></section>)}<section><h2>Due-diligence action plan</h2>{report.dueDiligence.map((d,i)=><p key={i}><b>{d.timing}</b> — {d.task} <i>({d.owner})</i></p>)}</section><section><h2>Limitations</h2><List title="Professional review notice" items={report.limitations}/></section><button className="printButton" type="button" onClick={()=>window.print()}>Print or save polished PDF</button></div>}</article>}
 </div></section>}
 <section className="notice"><strong>Professional-controlled workflow</strong><p>Research is decision support, not a title opinion, survey, legal advice, engineering certification, appraisal, zoning clearance, septic approval or guarantee. External communications and client delivery require human approval.</p></section></main>}
