"use client";
import type { ReportSection } from "./lib/report";

type SavedAction={id:string;priority:string;title:string;question:string;requested_return:string;status:string;response_text?:string|null};
type ActionFile={name:string;data:string};

const researchGroups=[
  {title:"Property and ownership",description:"Parcel identity, ownership and recorded-interest screening.",ids:["parcel","title"]},
  {title:"Land use and development",description:"Zoning, access, fire service and entitlement considerations.",ids:["zoning","access","fire"]},
  {title:"Physical feasibility",description:"Flood, water, wastewater, utilities and environmental constraints.",ids:["flood","water","septic","utilities","environment"]},
  {title:"Market and strategy",description:"Comparable evidence, value screening and negotiation implications.",ids:["market","negotiation"]}
];

function Findings({title,items,tone=""}:{title:string;items:string[];tone?:string}){if(!items.length)return null;return <div className={`researchList ${tone}`}><h4>{title}</h4><ul>{items.map((x,i)=><li key={i}>{x}</li>)}</ul></div>}

export function ResearchWorkspace({sections}:{sections:ReportSection[]}){
  return <article className="researchWorkspace"><div className="workspaceHeading"><p className="eyebrow">DEEP RESEARCH</p><h2>Research and evidence</h2><p>Every original discipline remains available. Open only the subjects needed for review; conclusions, risks, actions and consulted sources are preserved in full.</p></div>
    {researchGroups.map(group=><section className="researchGroup" key={group.title}><h3>{group.title}</h3><p>{group.description}</p><div className="researchCards">{group.ids.map(id=>sections.find(x=>x.id===id)).filter((x):x is ReportSection=>Boolean(x)).map(section=><details className="researchCard" key={section.id}><summary><span><b>{section.title}</b><small>{section.summary}</small></span><em className={`badge ${section.status.replaceAll(" ","").toLowerCase()}`}>{section.status}</em></summary><div className="researchBody"><div className="twoCol"><Findings title="Findings" items={section.findings}/><Findings title="Risk flags" items={section.risks} tone="risk"/><Findings title="Recommended actions" items={section.actions} tone="action"/><div className="researchList"><h4>Evidence register</h4>{section.sources.length?section.sources.map((s,i)=><p className="source" key={i}><b>{s.authority}</b> · <a href={s.url} target="_blank" rel="noreferrer">{s.title}</a><small>Accessed {s.accessed}</small></p>):<p>No directly matched source recorded.</p>}</div></div></div></details>)}</div></section>)}
  </article>
}

export function RequestsWorkspace({actions,answers,files,busy,running,onAnswer,onText,onPdf,onDisposition,onResearch}:{actions:SavedAction[];answers:Record<string,string>;files:Record<string,ActionFile>;busy:boolean;running:boolean;onAnswer:(id:string,append?:boolean)=>void;onText:(id:string,text:string)=>void;onPdf:(id:string,file?:File)=>void;onDisposition:(id:string,status:"not_applicable"|"deferred"|"dismissed"|"open")=>void;onResearch:(item:SavedAction)=>void}){
  const items=actions.filter(x=>!x.title.startsWith("[TC]")&&!["Structured deal inputs","Transaction coordinator setup"].includes(x.title));
  const open=items.filter(x=>x.status==="open").length;
  return <article className="requestsWorkspace"><div className="workspaceHeading"><p className="eyebrow">REQUESTS & TASKS</p><h2>{open} open information request(s)</h2><p>Answer, attach evidence, research only the affected discipline, or record why an item is not currently applicable.</p></div><div className="actionList">{items.length?items.map(x=><div className={`actionItem ${x.status}`} key={x.id}><div><span className={`priority ${x.priority}`}>{x.priority}</span><h4>{x.title}</h4><p>{x.question}</p><small>Requested return: {x.requested_return}</small></div>{x.status==="open"?<div><textarea value={answers[x.id]||""} onChange={e=>onText(x.id,e.target.value)} placeholder="Answer, document reference, portal result, or reason for disposition…"/><label className="actionFile">Attach PDF<input type="file" accept="application/pdf,.pdf" onChange={e=>onPdf(x.id,e.target.files?.[0])}/>{files[x.id]&&<small>{files[x.id].name} ready</small>}</label><button type="button" disabled={busy} onClick={()=>onAnswer(x.id)}>Save response</button><div className="requestDisposition"><button type="button" disabled={busy} onClick={()=>onDisposition(x.id,"not_applicable")}>Not applicable</button><button type="button" disabled={busy} onClick={()=>onDisposition(x.id,"deferred")}>Defer</button><button type="button" disabled={busy} onClick={()=>onDisposition(x.id,"dismissed")}>Dismiss</button></div></div>:<div className="answered"><b>{x.status.replaceAll("_"," ")}</b><p>{x.response_text}</p><textarea value={answers[x.id]||""} onChange={e=>onText(x.id,e.target.value)} placeholder="Add supplemental information…"/><label className="actionFile">Attach additional PDF<input type="file" accept="application/pdf,.pdf" onChange={e=>onPdf(x.id,e.target.files?.[0])}/>{files[x.id]&&<small>{files[x.id].name} ready</small>}</label><button type="button" disabled={busy} onClick={()=>onAnswer(x.id,true)}>Save additional information</button>{x.status==="answered"&&<button type="button" disabled={busy||running} onClick={()=>onResearch(x)}>Research this response</button>}{["not_applicable","deferred","dismissed"].includes(x.status)&&<button type="button" disabled={busy} onClick={()=>onDisposition(x.id,"open")}>Reopen request</button>}</div>}</div>):<p className="emptyState">No research requests are currently recorded.</p>}</div></article>
}
