import OpenAI from "openai";
import type { PropertyReport } from "../../lib/report";

export const maxDuration = 300;
const sectionIds = ["parcel", "title", "zoning", "access", "flood", "water", "septic", "utilities", "fire", "environment", "market", "negotiation"];
function normalizeApn(value: unknown) { const digits = String(value || "").replace(/\D/g, ""); return digits.length === 8 ? `${digits.slice(0,3)}-${digits.slice(3,5)}-${digits.slice(5)}` : null; }

const schema = { type:"object", additionalProperties:false, required:["apn","generatedAt","overallConfidence","decision","executiveSummary","verifiedFacts","criticalRisks","useRanking","sections","neededItems","dueDiligence","limitations"], properties:{
  apn:{type:"string"},generatedAt:{type:"string"},overallConfidence:{type:"string",enum:["High","Moderate","Low"]},decision:{type:"string"},executiveSummary:{type:"string"},verifiedFacts:{type:"array",items:{type:"string"}},criticalRisks:{type:"array",items:{type:"string"}},
  useRanking:{type:"array",items:{type:"object",additionalProperties:false,required:["use","rank","viability","conditions"],properties:{use:{type:"string"},rank:{type:"number"},viability:{type:"string"},conditions:{type:"array",items:{type:"string"}}}}},
  sections:{type:"array",items:{type:"object",additionalProperties:false,required:["id","title","status","summary","findings","risks","actions","sources"],properties:{id:{type:"string",enum:sectionIds},title:{type:"string"},status:{type:"string",enum:["Verified","Partially verified","Unverified","Not applicable"]},summary:{type:"string"},findings:{type:"array",items:{type:"string"}},risks:{type:"array",items:{type:"string"}},actions:{type:"array",items:{type:"string"}},sources:{type:"array",items:{type:"object",additionalProperties:false,required:["title","url","authority","accessed"],properties:{title:{type:"string"},url:{type:"string"},authority:{type:"string",enum:["Official","Professional","Market","Other"]},accessed:{type:"string"}}}}}}},
  neededItems:{type:"array",items:{type:"object",additionalProperties:false,required:["priority","item","why","provide"],properties:{priority:{type:"string",enum:["Critical","Important","Optional"]},item:{type:"string"},why:{type:"string"},provide:{type:"string"}}}},
  dueDiligence:{type:"array",items:{type:"object",additionalProperties:false,required:["timing","task","owner"],properties:{timing:{type:"string"},task:{type:"string"},owner:{type:"string"}}}},limitations:{type:"array",items:{type:"string"}}
}};

export async function POST(request: Request) {
  try {
    if (!process.env.OPENAI_API_KEY) return Response.json({ok:false,error:"The OpenAI connection is not configured."},{status:503});
    const body=await request.json(); const apn=normalizeApn(body.apn); const objective=String(body.objective||"General acquisition and highest-and-best-use analysis").trim().slice(0,1600); const knownInformation=String(body.knownInformation||"").trim().slice(0,6000); const propertyTypes=Array.isArray(body.propertyTypes)?body.propertyTypes.map(String).slice(0,4):[]; const fireService=String(body.fireService||"Unknown — research needed").slice(0,200);
    if(!apn)return Response.json({ok:false,error:"Enter a valid eight-digit Mohave County APN."},{status:400});
    const response=await new OpenAI({apiKey:process.env.OPENAI_API_KEY}).responses.create({model:process.env.OPENAI_MODEL||"gpt-5-mini",tools:[{type:"web_search"}],text:{format:{type:"json_schema",name:"property_report",strict:true,schema}},input:`Act as a rigorous Mohave County land-development research orchestrator. Target APN: ${apn}. Selected analysis tracks: ${propertyTypes.join(", ")}. Buyer objective: ${objective}. User-selected fire service: ${fireService}. User-provided facts/documents: ${knownInformation||"None"}.

SOURCE LADDER (follow in order): (1) establish APN identity and coordinates from Mohave County Assessor/GIS; (2) parcel attributes and mapped districts/layers; (3) Recorder/title leads; (4) official zoning ordinance and General Plan; (5) FEMA/county flood and drainage; (6) ADWR well registry and drillers-log leads; (7) county environmental health/septic; (8) utilities; (9) serving fire district and stored-water/access requirements; (10) environmental/public-land constraints; (11) market evidence. Prefer official sources. Market pages may locate leads but never verify legal facts.

MANDATORY ARIZONA DEEP DIVES: Search ADWR Well Registry/Wells55, available well reports and drillers-log leads; Mohave County zoning, General Plan, development and building ordinances; Mohave County Recorder deed/instrument leads; USDA NRCS Web Soil Survey/SSURGO soil units and development limitations; FEMA and county flood layers; applicable Arizona Revised Statutes. For Large Acreage / Subdivision, also search Arizona Department of Real Estate subdivision/public-report records, A.R.S. Title 32 subdivision requirements, water adequacy/assured-water requirements, legal lot status, subdivision and minor-land-division paths, preliminary lot yield, road/infrastructure standards and utility/fire-flow implications. For Commercial, investigate zoning entitlement, site plan/SUP/rezoning, ADOT or county access, utility capacity, fire code, environmental review and market feasibility. For Residential, investigate building-code pathway, legal dwelling type, setbacks, permits, water, septic and fire access/storage. For Vacant Land, establish legal parcel/buildability and development constraints rather than assuming it is buildable.

HUMAN INTERFACE: Treat the fire-service selection and all user statements as USER-SUPPLIED until independently matched. If a portal needs login, CAPTCHA, acceptance, coordinates, owner name, document number, uploaded PDF, map printout, title commitment, survey, septic record, well registration or professional response, create a specific neededItems request explaining the exact portal/link, information needed and what the user should return. Never claim that an interactive search was completed if it was not.

COMPLETENESS GATE: Never silently omit an unavailable fact. Every unresolved fact affecting ownership, access, buildability, water, wastewater, flood, fire, utilities, use approval, subdivision, cost, value, or negotiation must appear in neededItems with exactly what the professional user should upload, type, or provide. Do not call something Verified unless the source directly matches this APN. Separate evidence, inference, risk and recommendation. Sources must be real URLs actually consulted. Keep each section concise but decision-useful.

The sections array must contain exactly these 12 ids in this order: ${sectionIds.join(", ")}. Evaluate tiny-home/cottage-community demand and feasibility explicitly in market. Rank highest-and-best-use scenarios. Provide decision conditions and negotiation leverage. Set generatedAt to the current ISO time.`});
    const report=JSON.parse(response.output_text) as PropertyReport; if(report.sections.length!==sectionIds.length)throw new Error("Incomplete section set"); return Response.json({ok:true,report});
  } catch(error){console.error("Analysis failed",error);return Response.json({ok:false,error:"The structured research request failed. Retry once; if it continues, review the Vercel function log."},{status:500});}
}
