import OpenAI from "openai";
import type { PropertyReport } from "../../lib/report";
import { getSupabaseAdmin } from "../../lib/supabase-admin";
import { resolveMohaveParcel } from "../../lib/parcel-resolver";
import { resolveSpatialOverlays } from "../../lib/spatial-overlays";
import { resolveAdwrWells } from "../../lib/adwr-wells";
import { resolveUsdaSoils } from "../../lib/usda-soils";
import { resolveRecorderLeads } from "../../lib/recorder-leads";
import { resolveMarketComps } from "../../lib/market-comps";
import { resolveBuildingDetails } from "../../lib/building-details";
import { resolveZoningRules } from "../../lib/zoning-rules";
import { resolveLandDivisionRules } from "../../lib/land-division-rules";
import { resolveHighestBestUse } from "../../lib/highest-best-use";
import { buildEvidencePackage } from "../../lib/evidence-package";
import { resolveValuationNegotiation } from "../../lib/valuation-negotiation";

export const maxDuration = 300;
const sectionIds = ["parcel", "title", "zoning", "access", "flood", "water", "septic", "utilities", "fire", "environment", "market", "negotiation"];
function normalizeApn(value: unknown) { const digits = String(value || "").replace(/\D/g, ""); return digits.length === 8 ? `${digits.slice(0,3)}-${digits.slice(3,5)}-${digits.slice(5)}` : null; }

async function fetchJson(url:string){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),18000);try{const response=await fetch(url,{signal:controller.signal,headers:{Accept:"application/json"},cache:"no-store"});if(!response.ok)throw new Error(`HTTP ${response.status}`);return await response.json()}finally{clearTimeout(timer)}}
async function femaEvidence(parcel:any){
  const geometry=parcel?.geometry;if(!geometry)return {status:"blocked",reason:"Parcel resolver exhausted its query ladder without returning a validated polygon."};
  const service="https://hazards.fema.gov/arcgis/rest/services/public/NFHL/MapServer/28/query";
  const params=new URLSearchParams({geometry:JSON.stringify(geometry),geometryType:"esriGeometryPolygon",inSR:"4326",spatialRel:"esriSpatialRelIntersects",outFields:"FLD_ZONE,ZONE_SUBTY,SFHA_TF,STATIC_BFE,DFIRM_ID",returnGeometry:"false",f:"json"});
  try{const data=await fetchJson(`${service}?${params}`);return {status:"queried",service,features:data.features||[],error:data.error||null}}catch(error){return {status:"unavailable",service,features:[],error:error instanceof Error?error.message:"FEMA service failed"}}
}

function compactEvidence(value:unknown,limit=14000){
  const serialized=JSON.stringify(value??null);return serialized.length<=limit?serialized:`${serialized.slice(0,limit)}\n[TRUNCATED AFTER ${limit} CHARACTERS — use cited source URL for remaining fields]`;
}
async function collect<T>(label:string,operation:()=>Promise<T>|T):Promise<T|{status:"connector_error";sourceStage:string;error:string}>{
  try{return await operation()}catch(error){console.error(`${label} connector failed`,error);return {status:"connector_error",sourceStage:label,error:error instanceof Error?error.message:"Unknown connector failure"}}
}
function fallbackNotes(title:string,assignment:string,evidence:Record<string,unknown>,reason:string){
  return `${title.toUpperCase()} — DETERMINISTIC EVIDENCE PRESERVED\nThe narrative/web-search pass could not start (${reason}). This is a recoverable worker failure, not a finding that public information is unavailable.\n\nASSIGNMENT\n${assignment}\n\nPUBLIC CONNECTOR RESULTS\n${Object.entries(evidence).map(([key,value])=>`${key}: ${compactEvidence(value,7000)}`).join("\n\n")}\n\nGAP PROTOCOL\nSynthesis must use the returned parcel-matched evidence, label connector errors separately, and create a targeted retry for only the unresolved source. It must not replace obtained facts with a generic third-party referral.`;
}
async function specialist(client:OpenAI,title:string,assignment:string,context:string,file?:{name:string;data:string}){
  const prompt=`You are the ${title} investigator for a Mohave County property due-diligence system. ${assignment}\n\nCASE CONTEXT:\n${context}\n\nMANDATORY DEPTH PROTOCOL\n1. Inventory every parcel-matched fact and exact identifier already returned by deterministic public connectors.\n2. Follow each material thread through the most specific official source available: Mohave GIS/Assessor/Recorder/Development Services and ordinances; ADWR/Wells55; FEMA NFHL; USDA NRCS/SSURGO; ADRE; and Arizona statutes as applicable.\n3. Revisit every unknown once using a second official query, alternate identifier, linked document, adjacent layer, or controlling rule. Do not stop at a portal landing page or generic agency link.\n4. Only after that second pass, classify a gap as: automation blocked, no public record located, conflicting evidence, or professional verification required. State searches attempted, exact URLs, identifiers, and the smallest human action needed.\n5. Derive supported comparisons and practical conclusions, but never turn an inference into a verified fact.\n\nRecord instrument numbers, registration numbers, map/layer attributes, dates, document links and controlling ordinance/statute sections when obtainable. Analyze supplied PDFs as user-provided evidence and corroborate material facts. Return concise, evidence-dense notes with headings: VERIFIED, SUPPORTED INFERENCES, CONFLICTS, SECOND-PASS SEARCHES, REMAINING GAPS, and PRACTICAL CONCLUSIONS.`;
  const input:any=file?[{role:"user",content:[{type:"input_text",text:prompt},{type:"input_file",filename:file.name,file_data:file.data}]}]:prompt;
  return await client.responses.create({model:process.env.OPENAI_MODEL||"gpt-5-mini",tools:[{type:"web_search"}],background:true,max_output_tokens:14000,input});
}

const schema = { type:"object", additionalProperties:false, required:["apn","generatedAt","overallConfidence","decision","executiveSummary","verifiedFacts","criticalRisks","useRanking","sections","neededItems","dueDiligence","limitations"], properties:{
  apn:{type:"string"},generatedAt:{type:"string"},overallConfidence:{type:"string",enum:["High","Moderate","Low"]},decision:{type:"string"},executiveSummary:{type:"string"},verifiedFacts:{type:"array",items:{type:"string"}},criticalRisks:{type:"array",items:{type:"string"}},
  useRanking:{type:"array",items:{type:"object",additionalProperties:false,required:["use","rank","viability","conditions"],properties:{use:{type:"string"},rank:{type:"number"},viability:{type:"string"},conditions:{type:"array",items:{type:"string"}}}}},
  sections:{type:"array",items:{type:"object",additionalProperties:false,required:["id","title","status","summary","findings","risks","actions","sources"],properties:{id:{type:"string",enum:sectionIds},title:{type:"string"},status:{type:"string",enum:["Verified","Partially verified","Unverified","Not applicable"]},summary:{type:"string"},findings:{type:"array",items:{type:"string"}},risks:{type:"array",items:{type:"string"}},actions:{type:"array",items:{type:"string"}},sources:{type:"array",items:{type:"object",additionalProperties:false,required:["title","url","authority","accessed"],properties:{title:{type:"string"},url:{type:"string"},authority:{type:"string",enum:["Official","Professional","Market","Other"]},accessed:{type:"string"}}}}}}},
  neededItems:{type:"array",items:{type:"object",additionalProperties:false,required:["priority","item","why","provide"],properties:{priority:{type:"string",enum:["Critical","Important","Optional"]},item:{type:"string"},why:{type:"string"},provide:{type:"string"}}}},
  dueDiligence:{type:"array",items:{type:"object",additionalProperties:false,required:["timing","task","owner"],properties:{timing:{type:"string"},task:{type:"string"},owner:{type:"string"}}}},limitations:{type:"array",items:{type:"string"}}
}};

export async function POST(request: Request) {
  try {
    if (!process.env.OPENAI_API_KEY) return Response.json({ok:false,error:"The OpenAI connection is not configured."},{status:503});
    const body=await request.json(); const apn=normalizeApn(body.apn); const objective=String(body.objective||"General property research and acquisition analysis").trim().slice(0,1600); const knownInformation=String(body.knownInformation||"").trim().slice(0,6000);const supplementalInformation=String(body.supplementalInformation||"").trim().slice(0,6000); const propertyTypes=Array.isArray(body.propertyTypes)?body.propertyTypes.map(String).slice(0,4):[];const purpose=String(body.purpose||"Purchase inquiry").slice(0,120);const researchModules=Array.isArray(body.researchModules)?body.researchModules.map(String).slice(0,20):["parcel","zoning","access","flood","market"]; const fireService=String(body.fireService||"Unknown — research needed").slice(0,200);const caseId=String(body.caseId||"");const db=getSupabaseAdmin();const hbuApplicable=purpose==="Development feasibility"||propertyTypes.some((x:string)=>["Vacant Land","Large Acreage / Subdivision"].includes(x))||/develop|subdiv|cottage|tiny home|rv park|rezone|entitle/i.test(objective);
    if(!apn)return Response.json({ok:false,error:"Enter a valid eight-digit Mohave County APN."},{status:400});
    const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});
    const action=String(body.action||"investigate");
    if(action==="poll"){
      const responseId=String(body.responseId||"");if(!responseId.startsWith("resp_"))return Response.json({ok:false,error:"Invalid research job identifier."},{status:400});
      const response=await client.responses.retrieve(responseId);if(response.status==="queued"||response.status==="in_progress")return Response.json({ok:true,status:response.status});
      if(response.status!=="completed"){const code=response.error?.code||response.incomplete_details?.reason||"unknown_error";const rawDetail=response.error?.message||"OpenAI did not return additional details.";const detail=rawDetail.replace(/organization\s+org-[A-Za-z0-9_-]+/gi,"your OpenAI organization");if(db&&body.jobId)await db.from("research_jobs").update({status:"failed",error_message:detail,completed_at:new Date().toISOString()}).eq("id",body.jobId);return Response.json({ok:false,code,error:`Research job failed [${code}]: ${detail}`},{status:code==="rate_limit_exceeded"?429:500})}
      if(body.jobType==="synthesis"||body.jobType==="targeted_synthesis"){const report=JSON.parse(response.output_text) as PropertyReport;if(body.evidencePackage)report.evidencePackage=body.evidencePackage;if(report.sections.length!==sectionIds.length)throw new Error("Incomplete section set");if(db&&caseId){const prior=await db.from("report_versions").select("version_number").eq("case_id",caseId).order("version_number",{ascending:false}).limit(1);const version=(prior.data?.[0]?.version_number||0)+1;await db.from("report_versions").insert({case_id:caseId,version_number:version,report_type:"internal",included_sections:report.sections.map(s=>s.id),report_data:report,approval_status:"draft"});if(body.jobType==="synthesis"&&report.neededItems.length)await db.from("action_requests").insert(report.neededItems.map(item=>({case_id:caseId,priority:item.priority.toLowerCase(),title:item.item,question:item.why,reason:item.why,requested_return:item.provide,status:"open"})));if(body.jobType==="targeted_synthesis"&&body.actionId)await db.from("action_requests").update({status:"completed",completed_at:new Date().toISOString()}).eq("id",String(body.actionId));await db.from("cases").update({status:report.neededItems.some(x=>x.priority==="Critical")?"waiting_for_input":"professional_review",confidence:report.overallConfidence.toLowerCase(),readiness:Math.max(25,100-report.neededItems.filter(x=>x.priority==="Critical").length*12-report.neededItems.filter(x=>x.priority==="Important").length*5)}).eq("id",caseId)}return Response.json({ok:true,status:"completed",report})}
      if(db&&body.jobId)await db.from("research_jobs").update({status:"completed",result_summary:response.output_text,confidence:"partially_verified",completed_at:new Date().toISOString()}).eq("id",body.jobId);return Response.json({ok:true,status:"completed",notes:response.output_text});
    }
    const assignments:Record<string,[string,string]>={
      parcel:["Parcel, GIS, access and flood","Resolve parcel identity, coordinates/polygon, parcel attributes, site address, zoning and last-sale layers, recorded bearings/distances, roads/right-of-way, FEMA NFHL intersection, county flood/drainage layers, and map export/image pathways."],
      recorder:["Recorder, title and legal","Search Recorder and assessor-indexed leads for deeds, document/instrument numbers, transfers, plats, easements and transaction history. Do not claim a complete title search. Identify publicly viewable deed-image links or exact human retrieval steps."],
      water:["Water, septic and soils","Search ADWR Well Registry/Wells55 for exact 55-registration numbers, reports, drillers logs, construction, depth, casing, water level and yield. Search county septic records/rules and USDA NRCS Web Soil Survey/SSURGO map units, hydrologic group and development/septic limitations."],
      zoning:["Zoning, building and subdivision","Determine parcel-specific zoning and General Plan evidence, permitted/conditional uses, setbacks, building/fire-code implications, subdivision or minor-land-division paths, ADRE public reports, relevant Arizona statutes, water adequacy and entitlement requirements."]
    };
    if(action==="investigate"){
      const kind=String(body.kind);const assignment=assignments[kind];if(!assignment)return Response.json({ok:false,error:"Unknown investigator."},{status:400});
      const county=["parcel","water","recorder","zoning"].includes(kind)?await collect("Mohave parcel",()=>resolveMohaveParcel(apn)):null;
      const resolvedCounty=county&&!("sourceStage" in county)?county:null;
      const spatial=(kind==="parcel"||kind==="recorder"||kind==="zoning")&&resolvedCounty?await collect("spatial overlays",()=>resolveSpatialOverlays(resolvedCounty)):null;
      const usableSpatial=spatial&&!("sourceStage" in spatial)?spatial:null;
      const recorder=kind==="recorder"&&resolvedCounty&&usableSpatial?await collect("recorder leads",()=>resolveRecorderLeads(resolvedCounty,usableSpatial)):null;
      const market=kind==="parcel"&&resolvedCounty&&researchModules.includes("market")?await collect("market comparables",()=>resolveMarketComps(resolvedCounty)):null;
      const buildings=kind==="parcel"&&resolvedCounty?await collect("building details",()=>resolveBuildingDetails([String(resolvedCounty.attributes?.PARCEL||resolvedCounty.attributes?.TAXPIN||apn)])):null;
      const zoningRules=(kind==="zoning"||kind==="parcel")&&resolvedCounty&&usableSpatial&&researchModules.some((x:string)=>["zoning","access","fire","utilities"].includes(x))?await collect("zoning rules",()=>resolveZoningRules(resolvedCounty,usableSpatial)):null;
      const usableZoning=zoningRules&&!("sourceStage" in zoningRules)?zoningRules:null;
      const landDivisionRules=(kind==="zoning"||kind==="parcel")&&resolvedCounty&&usableZoning&&researchModules.includes("zoning")?await collect("land division rules",()=>resolveLandDivisionRules(resolvedCounty,usableZoning)):null;
      const wells=(kind==="water"||kind==="parcel")&&resolvedCounty&&researchModules.includes("water")?await collect("ADWR wells",()=>resolveAdwrWells(resolvedCounty)):null;
      const soils=(kind==="water"||kind==="parcel")&&resolvedCounty&&researchModules.some((x:string)=>["septic","environment"].includes(x))?await collect("USDA soils",()=>resolveUsdaSoils(resolvedCounty)):null;
      const highestBestUse=hbuApplicable&&kind==="parcel"&&resolvedCounty&&researchModules.includes("market")?await collect("development use ranking",()=>resolveHighestBestUse(resolvedCounty,buildings,usableSpatial,usableZoning,landDivisionRules,wells,soils,market)):null;
      const valuationNegotiation=kind==="parcel"&&resolvedCounty&&researchModules.includes("negotiation")?await collect("valuation negotiation",()=>resolveValuationNegotiation(resolvedCounty,market,highestBestUse,`${knownInformation}\n${supplementalInformation}`)):null;
      const directEvidence={analysisScope:{developmentUseApplicable:hbuApplicable,instruction:hbuApplicable?"Include a development-use ranking supported by parcel evidence.":"Do not run, request, rank, or mention highest-and-best-use or alternative development uses for this case."},county,buildings,spatial,zoningRules,landDivisionRules,highestBestUse,valuationNegotiation,recorder,market,wells,soils};
      const context=[`APN ${apn}; purpose ${purpose}; modules ${researchModules.join(", ")}; tracks ${propertyTypes.join(", ")}; objective ${objective}; fire input ${fireService}; user facts ${knownInformation||"None"}; follow-up ${supplementalInformation||"None"}`,`MOHAVE PARCEL ${compactEvidence(county,12000)}`,`BUILDINGS ${compactEvidence(buildings,7000)}`,`SPATIAL ${compactEvidence(spatial,12000)}`,`ZONING RULES ${compactEvidence(zoningRules,10000)}`,`LAND DIVISION / ADRE ${compactEvidence(landDivisionRules,9000)}`,`HBU ${compactEvidence(highestBestUse,9000)}`,`VALUATION ${compactEvidence(valuationNegotiation,8000)}`,`RECORDER ${compactEvidence(recorder,10000)}`,`MARKET ${compactEvidence(market,12000)}`,`ADWR ${compactEvidence(wells,10000)}`,`SSURGO ${compactEvidence(soils,10000)}`].join("\n\n");
      const suppliedFile=body.supplementalFile&&String(body.supplementalFile.name||"").toLowerCase().endsWith(".pdf")?{name:String(body.supplementalFile.name).slice(0,180),data:String(body.supplementalFile.data||"")}:undefined;
      let response;try{response=await specialist(client,assignment[0],assignment[1],context,suppliedFile)}catch(error){const reason=error instanceof Error?error.message:"Narrative worker failed";console.error(`${kind} specialist failed after connector collection`,error);return Response.json({ok:true,kind,status:"completed",inlineCompleted:true,notes:fallbackNotes(assignment[0],assignment[1],directEvidence,reason),directEvidence,warning:"Narrative research will be retried as a targeted gap pass; collected public evidence was preserved."})}
      let jobId=null;if(db&&caseId){const saved=await db.from("research_jobs").insert({case_id:caseId,category:kind,research_question:assignment[1],source_system:kind==="parcel"?"Mohave GIS / FEMA / assessor sales / web":kind==="water"?"ADWR / USDA NRCS / web":kind==="recorder"?"Mohave Recorder / Assessor survey maps / web":kind==="zoning"?"Mohave zoning ordinance / GIS / web":"OpenAI web research",status:"running",materiality:"critical",attempt_count:1,openai_response_id:response.id,started_at:new Date().toISOString()}).select("id").single();jobId=saved.data?.id||null;await db.from("cases").update({status:"investigating"}).eq("id",caseId)}return Response.json({ok:true,kind,responseId:response.id,jobId,status:response.status,directEvidence});
    }
    if(action==="targeted_synthesize"){
      const priorReport=body.priorReport as PropertyReport|undefined;const followUp=body.followUp as {kind?:string;request?:string;response?:string;notes?:string}|undefined;
      if(!priorReport||!followUp?.notes)return Response.json({ok:false,error:"The saved report or follow-up research is missing."},{status:400});
      const response=await client.responses.create({model:process.env.OPENAI_MODEL||"gpt-5-mini",background:true,text:{format:{type:"json_schema",name:"property_report",strict:true,schema}},input:`You are updating a saved Mohave County property report after one targeted due-diligence response. Preserve every unaffected section and all prior verified facts. Reconcile only facts and conclusions materially affected by the new response and investigator notes. User-supplied information remains unverified unless the investigator independently corroborated it. Remove the resolved needed item only if the evidence actually resolves it; otherwise rewrite it precisely. Recalculate decision, confidence, risks, highest-and-best-use ranking and readiness implications only where warranted.\n\nAPN: ${apn}\nTARGET DISCIPLINE: ${followUp.kind}\nORIGINAL REQUEST: ${followUp.request}\nUSER RESPONSE: ${followUp.response}\nTARGETED INVESTIGATOR NOTES:\n${followUp.notes}\n\nPRIOR SAVED REPORT:\n${JSON.stringify(priorReport)}\n\nReturn the complete report with exactly these section ids in order: ${sectionIds.join(", ")}. Set generatedAt to current ISO time.`});
      return Response.json({ok:true,responseId:response.id,status:response.status});
    }
    if(action!=="synthesize")return Response.json({ok:false,error:"Unknown analysis action."},{status:400});
    const investigations=Array.isArray(body.investigations)?body.investigations.slice(0,4):[];if(investigations.length<2||investigations.length>4)return Response.json({ok:false,error:"One or more research stages did not finish."},{status:400});
    if(!hbuApplicable)for(const investigation of investigations)investigation.notes=`CASE SCOPE: This property and request do not trigger development-use analysis. Do not run, rank, request, or mention highest-and-best-use or alternative development concepts. Return useRanking as an empty array.\n\n${investigation.notes||""}`;
    const evidencePackage=buildEvidencePackage(investigations);const response=await client.responses.create({model:process.env.OPENAI_MODEL||"gpt-5-mini",background:true,text:{format:{type:"json_schema",name:"property_report",strict:true,schema}},input:`You are the lead analyst. Synthesize these selected independent investigations into a rigorous report for APN ${apn}. Preserve exact identifiers and parcel-matched evidence. Resolve contradictions; never upgrade inference to fact. Every blocked portal or missing record must become a precise neededItems request with the official URL, human action, and requested return data. Working purpose: ${purpose}. Selected modules: ${researchModules.join(", ")}. Selected tracks: ${propertyTypes.join(", ")}. Unselected disciplines must remain in the required section array but use status Not applicable and state that they were outside the user-selected scope. Buyer objective: ${objective}. Fire-service input: ${fireService}.\n\n${investigations.map((x:any,i:number)=>`--- INVESTIGATOR ${i+1} (${x.kind}) ---\n${x.notes}\nDIRECT EVIDENCE: ${JSON.stringify(x.directEvidence||{})}`).join("\n")}\n\nThe sections array must contain exactly these ids in order: ${sectionIds.join(", ")}. Sources must be actual consulted URLs. Set generatedAt to current ISO time.`});
    return Response.json({ok:true,responseId:response.id,status:response.status,evidencePackage});
  } catch(error){console.error("Analysis failed",error);return Response.json({ok:false,error:"The structured research request failed. Retry once; if it continues, review the Vercel function log."},{status:500});}
}
