import OpenAI from "openai";
import type { PropertyReport } from "../../lib/report";
import { getSupabaseAdmin } from "../../lib/supabase-admin";
import { resolveMohaveParcel } from "../../lib/parcel-resolver";
import { resolveSpatialOverlays } from "../../lib/spatial-overlays";
import { resolveAdwrWells } from "../../lib/adwr-wells";
import { resolveUsdaSoils } from "../../lib/usda-soils";
import { resolveRecorderLeads } from "../../lib/recorder-leads";
import { resolveMarketComps } from "../../lib/market-comps";
import { resolveBuildingDetails } from "../../lib/building-details";

export const maxDuration = 300;
const sectionIds = ["parcel", "title", "zoning", "access", "flood", "water", "septic", "utilities", "fire", "environment", "market", "negotiation"];
function normalizeApn(value: unknown) { const digits = String(value || "").replace(/\D/g, ""); return digits.length === 8 ? `${digits.slice(0,3)}-${digits.slice(3,5)}-${digits.slice(5)}` : null; }

async function fetchJson(url:string){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),18000);try{const response=await fetch(url,{signal:controller.signal,headers:{Accept:"application/json"},cache:"no-store"});if(!response.ok)throw new Error(`HTTP ${response.status}`);return await response.json()}finally{clearTimeout(timer)}}
async function femaEvidence(parcel:any){
  const geometry=parcel?.geometry;if(!geometry)return {status:"blocked",reason:"Parcel resolver exhausted its query ladder without returning a validated polygon."};
  const service="https://hazards.fema.gov/arcgis/rest/services/public/NFHL/MapServer/28/query";
  const params=new URLSearchParams({geometry:JSON.stringify(geometry),geometryType:"esriGeometryPolygon",inSR:"4326",spatialRel:"esriSpatialRelIntersects",outFields:"FLD_ZONE,ZONE_SUBTY,SFHA_TF,STATIC_BFE,DFIRM_ID",returnGeometry:"false",f:"json"});
  try{const data=await fetchJson(`${service}?${params}`);return {status:"queried",service,features:data.features||[],error:data.error||null}}catch(error){return {status:"unavailable",service,features:[],error:error instanceof Error?error.message:"FEMA service failed"}}
}

async function specialist(client:OpenAI,title:string,assignment:string,context:string,file?:{name:string;data:string}){const prompt=`You are the ${title} investigator for a Mohave County property due-diligence system. ${assignment}\n\nCASE CONTEXT:\n${context}\n\nGo beyond summaries. Search official record systems, ordinances, statutes, maps and technical sources. Record exact identifiers, document/instrument references, layer attributes, dates and URLs when obtainable. Analyze any supplied PDF as user-provided evidence and independently corroborate material facts when possible. Clearly distinguish direct parcel matches, geographic intersections, general rules, market claims and unresolved items. State the exact human portal action when automation is blocked. Return concise but evidence-dense investigator notes for a separate synthesis model.`;const input:any=file?[{role:"user",content:[{type:"input_text",text:prompt},{type:"input_file",filename:file.name,file_data:file.data}]}]:prompt;return await client.responses.create({model:process.env.OPENAI_MODEL||"gpt-5-mini",tools:[{type:"web_search"}],background:true,input})}

const schema = { type:"object", additionalProperties:false, required:["apn","generatedAt","overallConfidence","decision","executiveSummary","verifiedFacts","criticalRisks","useRanking","sections","neededItems","dueDiligence","limitations"], properties:{
  apn:{type:"string"},generatedAt:{type:"string"},overallConfidence:{type:"string",enum:["High","Moderate","Low"]},decision:{type:"string"},executiveSummary:{type:"string"},verifiedFacts:{type:"array",items:{type:"string"}},criticalRisks:{type:"array",items:{type:"string"}},
  useRanking:{type:"array",items:{type:"object",additionalProperties:false,required:["use","rank","viability","conditions"],properties:{use:{type:"string"},rank:{type:"number"},viability:{type:"string"},conditions:{type:"array",items:{type:"string"}}}}},
  sections:{type:"array",items:{type:"object",additionalProperties:false,required:["id","title","status","summary","findings","risks","actions","sources"],properties:{id:{type:"string",enum:sectionIds},title:{type:"string"},status:{type:"string",enum:["Verified","Partially verified","Unverified","Not applicable"]},summary:{type:"string"},findings:{type:"array",items:{type:"string"}},risks:{type:"array",items:{type:"string"}},actions:{type:"array",items:{type:"string"}},sources:{type:"array",items:{type:"object",additionalProperties:false,required:["title","url","authority","accessed"],properties:{title:{type:"string"},url:{type:"string"},authority:{type:"string",enum:["Official","Professional","Market","Other"]},accessed:{type:"string"}}}}}}},
  neededItems:{type:"array",items:{type:"object",additionalProperties:false,required:["priority","item","why","provide"],properties:{priority:{type:"string",enum:["Critical","Important","Optional"]},item:{type:"string"},why:{type:"string"},provide:{type:"string"}}}},
  dueDiligence:{type:"array",items:{type:"object",additionalProperties:false,required:["timing","task","owner"],properties:{timing:{type:"string"},task:{type:"string"},owner:{type:"string"}}}},limitations:{type:"array",items:{type:"string"}}
}};

export async function POST(request: Request) {
  try {
    if (!process.env.OPENAI_API_KEY) return Response.json({ok:false,error:"The OpenAI connection is not configured."},{status:503});
    const body=await request.json(); const apn=normalizeApn(body.apn); const objective=String(body.objective||"General acquisition and highest-and-best-use analysis").trim().slice(0,1600); const knownInformation=String(body.knownInformation||"").trim().slice(0,6000);const supplementalInformation=String(body.supplementalInformation||"").trim().slice(0,6000); const propertyTypes=Array.isArray(body.propertyTypes)?body.propertyTypes.map(String).slice(0,4):[]; const fireService=String(body.fireService||"Unknown — research needed").slice(0,200);const caseId=String(body.caseId||"");const db=getSupabaseAdmin();
    if(!apn)return Response.json({ok:false,error:"Enter a valid eight-digit Mohave County APN."},{status:400});
    const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});
    const action=String(body.action||"investigate");
    if(action==="poll"){
      const responseId=String(body.responseId||"");if(!responseId.startsWith("resp_"))return Response.json({ok:false,error:"Invalid research job identifier."},{status:400});
      const response=await client.responses.retrieve(responseId);if(response.status==="queued"||response.status==="in_progress")return Response.json({ok:true,status:response.status});
      if(response.status!=="completed"){const code=response.error?.code||response.incomplete_details?.reason||"unknown_error";const rawDetail=response.error?.message||"OpenAI did not return additional details.";const detail=rawDetail.replace(/organization\s+org-[A-Za-z0-9_-]+/gi,"your OpenAI organization");if(db&&body.jobId)await db.from("research_jobs").update({status:"failed",error_message:detail,completed_at:new Date().toISOString()}).eq("id",body.jobId);return Response.json({ok:false,code,error:`Research job failed [${code}]: ${detail}`},{status:code==="rate_limit_exceeded"?429:500})}
      if(body.jobType==="synthesis"||body.jobType==="targeted_synthesis"){const report=JSON.parse(response.output_text) as PropertyReport;if(report.sections.length!==sectionIds.length)throw new Error("Incomplete section set");if(db&&caseId){const prior=await db.from("report_versions").select("version_number").eq("case_id",caseId).order("version_number",{ascending:false}).limit(1);const version=(prior.data?.[0]?.version_number||0)+1;await db.from("report_versions").insert({case_id:caseId,version_number:version,report_type:"internal",included_sections:report.sections.map(s=>s.id),report_data:report,approval_status:"draft"});if(body.jobType==="synthesis"&&report.neededItems.length)await db.from("action_requests").insert(report.neededItems.map(item=>({case_id:caseId,priority:item.priority.toLowerCase(),title:item.item,question:item.why,reason:item.why,requested_return:item.provide,status:"open"})));if(body.jobType==="targeted_synthesis"&&body.actionId)await db.from("action_requests").update({status:"completed",completed_at:new Date().toISOString()}).eq("id",String(body.actionId));await db.from("cases").update({status:report.neededItems.some(x=>x.priority==="Critical")?"waiting_for_input":"professional_review",confidence:report.overallConfidence.toLowerCase(),readiness:Math.max(25,100-report.neededItems.filter(x=>x.priority==="Critical").length*12-report.neededItems.filter(x=>x.priority==="Important").length*5)}).eq("id",caseId)}return Response.json({ok:true,status:"completed",report})}
      if(db&&body.jobId)await db.from("research_jobs").update({status:"completed",result_summary:response.output_text,confidence:"partially_verified",completed_at:new Date().toISOString()}).eq("id",body.jobId);return Response.json({ok:true,status:"completed",notes:response.output_text});
    }
    const assignments:Record<string,[string,string]>={
      parcel:["Parcel, GIS, access and flood","Resolve parcel identity, coordinates/polygon, parcel attributes, site address, zoning and last-sale layers, recorded bearings/distances, roads/right-of-way, FEMA NFHL intersection, county flood/drainage layers, and map export/image pathways."],
      recorder:["Recorder, title and legal","Search Recorder and assessor-indexed leads for deeds, document/instrument numbers, transfers, plats, easements and transaction history. Do not claim a complete title search. Identify publicly viewable deed-image links or exact human retrieval steps."],
      water:["Water, septic and soils","Search ADWR Well Registry/Wells55 for exact 55-registration numbers, reports, drillers logs, construction, depth, casing, water level and yield. Search county septic records/rules and USDA NRCS Web Soil Survey/SSURGO map units, hydrologic group and development/septic limitations."],
      zoning:["Zoning, building and subdivision","Determine parcel-specific zoning and General Plan evidence, permitted/conditional uses, setbacks, building/fire-code implications, subdivision or minor-land-division paths, ADRE public reports, relevant Arizona statutes, water adequacy and entitlement requirements."]
    };
    if(action==="investigate"){
      const kind=String(body.kind);const assignment=assignments[kind];if(!assignment)return Response.json({ok:false,error:"Unknown investigator."},{status:400});
      const county=["parcel","water","recorder"].includes(kind)?await resolveMohaveParcel(apn):null;const spatial=(kind==="parcel"||kind==="recorder")&&county?await resolveSpatialOverlays(county):null;const recorder=kind==="recorder"&&county&&spatial?await resolveRecorderLeads(county,spatial):null;const market=kind==="parcel"&&county?await resolveMarketComps(county):null;const buildings=kind==="parcel"&&county?await resolveBuildingDetails([String(county.attributes?.PARCEL||county.attributes?.TAXPIN||apn)]):null;const [wells,soils]=kind==="water"&&county?await Promise.all([resolveAdwrWells(county),resolveUsdaSoils(county)]):[null,null];
      const context=`APN ${apn}; tracks ${propertyTypes.join(", ")}; objective ${objective}; fire input ${fireService}; user information ${knownInformation||"None"}; targeted follow-up information ${supplementalInformation||"None"}; OFFICIAL MOHAVE PARCEL EVIDENCE ${JSON.stringify(county).slice(0,24000)}; ASSESSOR BUILDING CHARACTERISTICS ${JSON.stringify(buildings).slice(0,12000)}; DETERMINISTIC SPATIAL INTERSECTIONS ${JSON.stringify(spatial).slice(0,18000)}; DETERMINISTIC RECORDER AND SURVEY LEADS ${JSON.stringify(recorder).slice(0,22000)}; ASSESSOR-RECORDED COMPARABLE SALE CANDIDATES ${JSON.stringify(market).slice(0,26000)}; OFFICIAL ADWR WELL REGISTRY RESULTS ${JSON.stringify(wells).slice(0,22000)}; OFFICIAL USDA SSURGO SOIL AND SEPTIC RESULTS ${JSON.stringify(soils).slice(0,22000)}`;
      const suppliedFile=body.supplementalFile&&String(body.supplementalFile.name||"").toLowerCase().endsWith(".pdf")?{name:String(body.supplementalFile.name).slice(0,180),data:String(body.supplementalFile.data||"")}:undefined;const response=await specialist(client,assignment[0],assignment[1],context,suppliedFile);let jobId=null;if(db&&caseId){const saved=await db.from("research_jobs").insert({case_id:caseId,category:kind,research_question:assignment[1],source_system:kind==="parcel"?"Mohave GIS / FEMA / assessor sales / web":kind==="water"?"ADWR / USDA NRCS / web":kind==="recorder"?"Mohave Recorder / Assessor survey maps / web":"OpenAI web research",status:"running",materiality:"critical",attempt_count:1,openai_response_id:response.id,started_at:new Date().toISOString()}).select("id").single();jobId=saved.data?.id||null;await db.from("cases").update({status:"investigating"}).eq("id",caseId)}return Response.json({ok:true,kind,responseId:response.id,jobId,status:response.status,directEvidence:{county,buildings,spatial,recorder,market,wells,soils}});
    }
    if(action==="targeted_synthesize"){
      const priorReport=body.priorReport as PropertyReport|undefined;const followUp=body.followUp as {kind?:string;request?:string;response?:string;notes?:string}|undefined;
      if(!priorReport||!followUp?.notes)return Response.json({ok:false,error:"The saved report or follow-up research is missing."},{status:400});
      const response=await client.responses.create({model:process.env.OPENAI_MODEL||"gpt-5-mini",background:true,text:{format:{type:"json_schema",name:"property_report",strict:true,schema}},input:`You are updating a saved Mohave County property report after one targeted due-diligence response. Preserve every unaffected section and all prior verified facts. Reconcile only facts and conclusions materially affected by the new response and investigator notes. User-supplied information remains unverified unless the investigator independently corroborated it. Remove the resolved needed item only if the evidence actually resolves it; otherwise rewrite it precisely. Recalculate decision, confidence, risks, highest-and-best-use ranking and readiness implications only where warranted.\n\nAPN: ${apn}\nTARGET DISCIPLINE: ${followUp.kind}\nORIGINAL REQUEST: ${followUp.request}\nUSER RESPONSE: ${followUp.response}\nTARGETED INVESTIGATOR NOTES:\n${followUp.notes}\n\nPRIOR SAVED REPORT:\n${JSON.stringify(priorReport)}\n\nReturn the complete report with exactly these section ids in order: ${sectionIds.join(", ")}. Set generatedAt to current ISO time.`});
      return Response.json({ok:true,responseId:response.id,status:response.status});
    }
    if(action!=="synthesize")return Response.json({ok:false,error:"Unknown analysis action."},{status:400});
    const investigations=Array.isArray(body.investigations)?body.investigations.slice(0,4):[];if(investigations.length!==4)return Response.json({ok:false,error:"One or more research stages did not finish."},{status:400});
    const response=await client.responses.create({model:process.env.OPENAI_MODEL||"gpt-5-mini",background:true,text:{format:{type:"json_schema",name:"property_report",strict:true,schema}},input:`You are the lead analyst. Synthesize these four independent investigations into a rigorous report for APN ${apn}. Preserve exact identifiers and parcel-matched evidence. Resolve contradictions; never upgrade inference to fact. Every blocked portal or missing record must become a precise neededItems request with the official URL, human action, and requested return data. Selected tracks: ${propertyTypes.join(", ")}. Buyer objective: ${objective}. Fire-service input: ${fireService}.\n\n${investigations.map((x:any,i:number)=>`--- INVESTIGATOR ${i+1} (${x.kind}) ---\n${x.notes}\nDIRECT EVIDENCE: ${JSON.stringify(x.directEvidence||{})}`).join("\n")}\n\nThe sections array must contain exactly these ids in order: ${sectionIds.join(", ")}. Sources must be actual consulted URLs. Set generatedAt to current ISO time.`});
    return Response.json({ok:true,responseId:response.id,status:response.status});
  } catch(error){console.error("Analysis failed",error);return Response.json({ok:false,error:"The structured research request failed. Retry once; if it continues, review the Vercel function log."},{status:500});}
}
