import { getSupabaseAdmin } from "../../../../lib/supabase-admin";

function validId(value:string){return /^[0-9a-f]{8}-[0-9a-f-]{27}$/i.test(value)}
const fields=["titleContact","titleEmail","surveyorContact","surveyorEmail","septicContact","septicEmail","contractorContact","contractorEmail","fireContact","fireEmail","lenderContact","lenderEmail","acceptanceDate","inspectionDeadline","titleDeadline","closingDate","coordinationNotes"] as const;
function draft(to:string,subject:string,body:string){return `DRAFT — HUMAN APPROVAL REQUIRED\nTO: ${to||"Contact email needed"}\nSUBJECT: ${subject}\n\n${body}`}

export async function PUT(request:Request,{params}:{params:Promise<{id:string}>}){
  const {id}=await params;if(!validId(id))return Response.json({ok:false,error:"Invalid case identifier."},{status:400});const body=await request.json();const inputs:any=Object.fromEntries(fields.map(key=>[key,String(body.inputs?.[key]||"").trim().slice(0,2500)]));const db=getSupabaseAdmin();if(!db)return Response.json({ok:false,error:"Supabase is not configured."},{status:503});const caseRow=await db.from("cases").select("apn").eq("id",id).single();if(caseRow.error)return Response.json({ok:false,error:caseRow.error.message},{status:404});
  const existing=await db.from("action_requests").select("id").eq("case_id",id).eq("title","Transaction coordinator setup").order("created_at",{ascending:false}).limit(1);if(existing.error)return Response.json({ok:false,error:existing.error.message},{status:500});const setup={case_id:id,priority:"important",title:"Transaction coordinator setup",question:"Structured contacts and contract milestones.",reason:"Controls the human-approved transaction workflow.",requested_return:"Contacts, emails, deadlines and coordination notes.",response_text:JSON.stringify(inputs),status:"answered",completed_at:new Date().toISOString()};const saved=existing.data?.[0]?.id?await db.from("action_requests").update(setup).eq("id",existing.data[0].id).select("*").single():await db.from("action_requests").insert(setup).select("*").single();if(saved.error)return Response.json({ok:false,error:`Could not preserve setup: ${saved.error.message}`},{status:500});
  if(!body.generate)return Response.json({ok:true,setup:saved.data,tasksCreated:0});const apn=caseRow.data.apn;const tasks=[
    {title:"[TC] Title and escrow opening/status",priority:"critical",question:draft(inputs.titleEmail,`APN ${apn} — title/escrow status and document request`,`Please confirm the escrow number, vesting instructions, title commitment schedule, exceptions requiring review, tax status, access exceptions and outstanding requirements. Return the title commitment and all referenced access/easement documents.`),requested_return:"Title commitment, escrow number, exception documents and status reply."},
    {title:"[TC] Survey and access verification",priority:"important",question:draft(inputs.surveyorEmail,`APN ${apn} — survey/access scope and scheduling`,`Please provide scope, fee and availability to verify parcel boundaries, encroachments, roadway/easement geometry and the effect, if any, of the mapped Panther Pass abandonment. Identify deliverables and turnaround time.`),requested_return:"Survey proposal, schedule and final signed deliverable."},
    {title:"[TC] Septic records and inspection",priority:"critical",question:draft(inputs.septicEmail,`APN ${apn} — septic records, capacity and inspection`,`Please confirm available permit records, system type/capacity and inspection availability. Evaluate suitability for the existing use and identify additional investigation needed for any proposed accessory residences.`),requested_return:"Permit records, inspection report, capacity finding and repair/design estimate."},
    {title:"[TC] Contractor condition and cost review",priority:"important",question:draft(inputs.contractorEmail,`APN ${apn} — improvement condition and cure-cost review`,`Please review the residence, equipment building and material inspection findings. Provide prioritized repair/correction scope, permit concerns, budget ranges and timing.`),requested_return:"Written scope, budget and schedule."},
    {title:"[TC] Fire access and stored-water requirements",priority:"important",question:draft(inputs.fireEmail,`APN ${apn} — fire access and stored-water confirmation`,`Please confirm service jurisdiction and applicable apparatus access, turnaround, driveway, addressing, defensible-space and on-site stored-water requirements for the existing and proposed residential use.`),requested_return:"Written jurisdiction and requirement confirmation."},
    {title:"[TC] Financing and appraisal milestones",priority:"important",question:draft(inputs.lenderEmail,`APN ${apn} — financing/appraisal milestone confirmation`,`Please confirm loan status, remaining borrower/property conditions, appraisal ordering and due date, underwriting milestones and expected clear-to-close timing.`),requested_return:"Written financing milestone and condition update."}
  ];let changed=0;for(const task of tasks){const match=await db.from("action_requests").select("id,status").eq("case_id",id).eq("title",task.title).order("created_at",{ascending:false}).limit(1);if(match.data?.[0]?.id){if(match.data[0].status!=="completed"){await db.from("action_requests").update({...task,reason:"Human-approved transaction coordination draft.",status:"open",response_text:null,completed_at:null}).eq("id",match.data[0].id);changed++}}else{await db.from("action_requests").insert({case_id:id,...task,reason:"Human-approved transaction coordination draft.",status:"open"});changed++}}
  const deadlines=[["Inspection",inputs.inspectionDeadline],["Title review",inputs.titleDeadline],["Closing",inputs.closingDate]].filter((x:any)=>x[1]);for(const [name,date] of deadlines as string[][]){const title=`[TC] Deadline — ${name}: ${date}`;const match=await db.from("action_requests").select("id").eq("case_id",id).eq("title",title).limit(1);if(!match.data?.length){await db.from("action_requests").insert({case_id:id,priority:name==="Closing"?"critical":"important",title,question:`Confirm completion readiness before the ${name.toLowerCase()} deadline. Escalate unresolved material items for professional decision.`,reason:"Contract deadline tracking.",requested_return:"Completion confirmation, extension decision or escalation note.",status:"open"});changed++}}
  return Response.json({ok:true,setup:saved.data,tasksCreated:changed});
}
